<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Godana')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/jquery.min.js')
            ->appendFile($this->basePath() . '/js/bootstrap.min.js')    
            ->appendFile($this->basePath() . '/js/jquery.placeholder.min.js')
            ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
<style type="text/css">
.sdfe {
    display: inline-block !important;
}
</style>
    </head>
    <body>
    	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand gdn-brand" href="<?=$this->url('home', array(), array(), true) ?>">godana</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                    	<li class="<?=$this->home_active; ?>">
                        	<a href="<?=$this->url('home', array(), array(), true) ?>"  title="<?=$this->translate('Home');?>"><i class="fa fa-home fa-lg"></i> <span class="menu-text"><?=$this->translate('Home');?></span></a>
                        </li>
                        <li class="<?=$this->bid_active; ?>">
                            <a href="<?=$this->url('bid', array('type' => null, 'categoryIdent' => null), array(), true) ?>" title="<?=$this->translate('Bid');?>"><i class="fa fa-exchange fa-lg"></i> <span class="menu-text"><?=$this->translate('Bid');?></span></a>
                        </li>                        
                        <li class="<?=$this->shop_active; ?>">
                            <a href="<?=$this->url('shop', array('categoryIdent' => null), array(), true) ?>" title="<?=$this->translate('Shop');?>"><i class="fa fa-shopping-cart fa-lg"></i> <span class="menu-text"><?=$this->translate('Shop');?></span></a>
                        </li>
                        <!-- <li class="<?=$this->feed_active; ?>">
                            <a href="<?=$this->url('tools/feed', array(), true) ?>" title="<?=$this->translate('Feed');?>"><i class="fa fa-th fa-lg"></i> <span class="menu-text"><?=$this->translate('Feed');?></span></a>
                        </li>-->  
                        <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-th-large fa-lg"></i> Fanampiny <i class="caret"></i>
                                <!-- <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $this->zfcUserDisplayName() ?> <i class="caret"></i>-->

                                </a>
                                <ul class="dropdown-menu">
                                	<li>
                                        <a tabindex="-1" href="#"><i class="fa fa-truck fa-lg"></i> Fitaterana</a>
                                    </li>
                                    <li class="divider"></li>
                                	<li>
                                        <a tabindex="-1" href="#"><i class="fa fa-thumbs-up fa-lg"></i> Mahasoa</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a tabindex="-1" href="#"><i class="fa fa-globe fa-lg"></i> Mahafinaritra</a>
                                    </li>
                                    <li class="divider"></li>	                               
                                    <li>
                                        <a href="<?=$this->url('tools/feed', array(), true) ?>" title="<?=$this->translate('Feed');?>"><i class="fa fa-users fa-lg"></i> <span class="menu-text"><?=$this->translate('Feed');?></span></a>
                                    </li>
                                    	                                    
                                    
                                    
                                </ul>
                            </li>                      
                    </ul>
                    <form class="navbar-form navbar-left navbar-search" role="search" action="<?php echo $this->url('search', array(), array(), true) ?>" method="get">
					  <span class="col-md-11 col-sm-11 input-group-sm">
    				    	<input type="text" class="form-control search-text" placeholder="<?=$this->translate('Search'); ?>" name="q" autocomplete="off">							
							<span class="icon-search">
								<button class="btn icon" type="submit">
								<i class=" glyphicon glyphicon-search"></i></button>
							</span>
    				    </span>
					</form>
                    <ul class="nav navbar-nav navbar-right">
                         <? if ($this->zfcUserIdentity()):?>
                            	<li class="dropdown">
	                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><img src="<?=$this->userPicture('xs'); ?>"> <i class="caret"></i>
	                                <!-- <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <?php echo $this->zfcUserDisplayName() ?> <i class="caret"></i>-->
	
	                                </a>
	                                <ul class="dropdown-menu">	                               
	                                    <li>
	                                        <a tabindex="-1" href="<?php echo $this->url('zfcuser/profile', array(), array(), true) ?>"><i class="fa fa-user"></i> <? echo $this->translate('Profile');?></a>
	                                    </li>
	                                    <li class="divider"></li>
	                                    <? 
	                                    $roles = $this->currentUserRole();
	                                    $isAdmin = false;
	                                    $isShopOwner = false;	
	                                    $isCooperative = false;
	                                    foreach ($roles as $role) {
	                                    	if ($role->getRoleId() == 'admin') {
	                                    		$isAdmin = true;
	                                    	}
	                                    	if ($role->getRoleId() == 'shop-owner') {
	                                    		$isShopOwner = true;
	                                    	}
	                                    	if (strpos($role->getRoleId(), 'cooperative') === 0) {
	                                    		$isCooperative = true;
	                                    	}
	                                    }                    
	                                    if ($isAdmin):?>
	                                    <li>
	                                        <a tabindex="-1" href="<?=$this->url('admin', array(), array(), true); ?>"><i class="fa fa-gear"></i> <? echo $this->translate('Admin');?></a>
	                                    </li>
	                                    <li class="divider"></li>
	                                    <? endif;?>
	                                    <? if ($isShopOwner && !$isAdmin): ?>
	                                    <li>
	                                        <a tabindex="-1" href="<?=$this->url('admin', array(), array(), true); ?>"><i class="fa fa-gear"></i> <? echo $this->translate('Admin');?></a>
	                                    </li>
	                                    <li class="divider"></li>
	                                    <? endif;?>
	                                    <? if ($isCooperative || $isAdmin): ?>
	                                    <li>
	                                        <a tabindex="-1" href="<?=$this->url('admin/cooperative', array(), array(), true) ?>"><i class="fa fa-gear"></i> <? echo $this->translate('Cooperative');?></a>
	                                    </li>
	                                    <li class="divider"></li>
	                                    <? endif;?>
	                                    <li>
	                                        <a tabindex="-1" href="<?php echo $this->url('zfcuser/logout', array(), array(), true) ?>"><i class="fa fa-power-off"></i> <?php echo $this->translate('Sign Out'); ?></a>
	                                    </li>
	                                    
	                                </ul>
	                            </li>
                            <? else: ?>
                            	<li><a href="<?php echo $this->url('zfcuser/login', array(), array(), true); ?>"><? echo $this->translate('Login');?></a></li>
                            <? endif;?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!-- /.container -->
        </nav>        
        
        <div class="container main-content">
            <?php echo $this->content; ?>
            <?
            $services = $this->getHelperPluginManager()->getServiceLocator();
			$router = $services->get('router');
			$request = $services->get('request');
			
			$routeMatch = $router->match($request);
			
			if (isset($routeMatch)) {
				$routeName = $routeMatch->getMatchedRouteName();
				$routeParams = $routeMatch->getParams();
	            $params = $request->getUri()->getQuery();
	            
				$routeParamsEn = $routeParams;
				if (array_key_exists('lang', $routeParamsEn)) {
					$routeParamsEn['lang'] = 'en';
	                $url_en = $this->url($routeName, $routeParamsEn);                
	                if (strlen($params) > 0) {                    
	                    $url_en .= '?'.$params;    
	                }
				}
				$routeParamsFr = $routeParams;
				if (array_key_exists('lang', $routeParamsFr)) {
					$routeParamsFr['lang'] = 'fr';
	                $url_fr = $this->url($routeName, $routeParamsFr);
	                if (strlen($params) > 0) {                    
	                    $url_fr .= '?'.$params;    
	                }	
				}
				$routeParamsMg = $routeParams;
				if (array_key_exists('lang', $routeParamsMg)) {
					$routeParamsMg['lang'] = 'mg';	
	                $url_mg = $this->url($routeName, $routeParamsMg);
	                if (strlen($params) > 0) {                    
	                    $url_mg .= '?'.$params;    
	                }
				}		
			}
			
            ?>
        </div><!-- /.container -->
		<div class="container">
            <hr>
            <footer>
                <div class="row">
                	<div class="col-md-5"><h5>&copy; <?=date('Y'); ?> Godana LLC. All rights reserved.</h5></div>
                	<div class="col-md-5 col-xs-12">
                		<div class="btn-group">
				  			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
				  				<?=$this->translate('Language');  ?>: <span class="selection label label-primary"><?=strtoupper($this->lang); ?></span>&nbsp;<span class="caret"></span>
				  			</button>
				  			<ul class="dropdown-menu" role="menu">
				  				<li><a href="<?=$url_en; ?>">EN</a></li>
				    			<li class="divider"></li>
				    			<li><a href="<?=$url_fr; ?>">FR</a></li>
				    			<li class="divider"></li>
				    			<li><a href="<?=$url_mg; ?>">MG</a></li>
				  			</ul>
						</div>
                	</div>
                </div>
            </footer>
        </div> <!-- /container -->            
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
        $(function() {
        	$('input, textarea').placeholder();
        });
        </script>
    </body>
</html>
