<?php if ($this->pageCount): ?>
<ul class="pagination pull-right">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="<?php echo $this->url($this->route, array('lang' => $this->lang, 'type' => $this->typeBid, 'categoryIdent' => $this->categoryIdent, 'page' => $this->previous)); ?>">
 &larr; <?=$this->translate('Previous') ?>
  </a></li>
<?php else: ?>
  <li class="disabled"><a href="#">&larr; <?=$this->translate('Previous') ?></a></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
 <li><a href="<?php echo $this->url($this->route, array('lang' => $this->lang, 'type' => $this->typeBid, 'categoryIdent' => $this->categoryIdent, 'page' => $page)); ?>">
  <?php echo $page; ?>
 </a></li>
  <?php else: ?>
 <li class="active"><a href="#"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a href="<?php echo $this->url($this->route, array('lang' => $this->lang, 'type' => $this->typeBid, 'categoryIdent' => $this->categoryIdent, 'page' => $this->next)); ?>">
 <?=$this->translate('Next') ?> &rarr;
  </a></li>
<?php else: ?>
  <li class="disabled"><a href="#"><?=$this->translate('Next') ?> &rarr;</a></li>
<?php endif; ?>
</ul>
<?php endif; ?>