<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')?>
<? $this->headTitle($this->translate('Admin Cooperative'));?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Add car line'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Car line added successfully.'); ?> 
</div>
<? endif;?>
<?php
$form = $this->lineCarForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/cooperative/line_car_add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<? $lineCar = $form->get('line-car-form'); ?>

<? $cooperative = $lineCar->get('cooperative'); ?>
<div class="form-group <?php if($this->formElementErrors($cooperative)) 
echo "has-error" ?>">
<?php echo $this->formLabel($cooperative); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($cooperative) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($cooperative); ?>
</div>
</div>

<? $zone = $lineCar->get('zone'); ?>
<div class="form-group <?php if($this->formElementErrors($zone)) 
echo "has-error" ?>">
<?php echo $this->formLabel($zone); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($zone) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($zone); ?>
</div>
</div>

<? $line = $lineCar->get('line'); ?>
<div class="form-group <?php if($this->formElementErrors($line)) 
echo "has-error" ?>">
<?php echo $this->formLabel($line); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($line) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($line); ?>
</div>
</div>
<? $car = $lineCar->get('car'); ?>
<div class="form-group <?php if($this->formElementErrors($car)) 
echo "has-error" ?>">
<?php echo $this->formLabel($car); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($car) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($car); ?>
</div>
</div>

<? $seats = $lineCar->get('seats'); ?>
<div class="form-group <?php if($this->formElementErrors($seats)) 
echo "has-error" ?>">
<?php echo $this->formLabel($seats); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($seats) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($seats); ?>
</div>
</div>

<? $column = $lineCar->get('column'); ?>
<div class="form-group <?php if($this->formElementErrors($column)) 
echo "has-error" ?>">
<?php echo $this->formLabel($column); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($column) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($column); ?>
</div>
</div>

<? $fare = $lineCar->get('fare'); ?>
<div class="form-group <?php if($this->formElementErrors($fare)) 
echo "has-error" ?>">
<?php echo $this->formLabel($fare); ?>
<div class="gdn_input_margin">
<div class="input-group">
<?php echo $this->formElement($fare) ?>
<span class="input-group-addon">Ariary</span>
</div>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($fare); ?>    
</div>
</div>

<? echo $this->formHidden($form->get('csrf'));?>
<div class="fd_action pull-right">
	<?=$this->formElement($form->get('submit'));?>
</div>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')?>
			
<script type="text/javascript">
var url = "<?=$this->url('admin/cooperative/line_car_ajax', array(), array(), true); ?>";
$(function() {	
	$(".cooperative-select").select2({
		minimumResultsForSearch: 10		
	}).on('change', function(event){
		if(event.target == this){
			var cooperativeId = event.val;
			$(".zone-select").off('change');
			$(".zone-select").select2({
				placeholder: "Select zone",
				minimumResultsForSearch: 10,
				ajax: {
			        url: url+"?cooperativeId="+cooperativeId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data.zone};
			        }
			    }
			}).on('change', function(event){
				if(event.target == this){
					var zoneId = event.val;
					$(".line-select").off('change');
					$(".line-select").select2({
						placeholder: "Select line",
						minimumResultsForSearch: 10,
						ajax: {
							url: url+"?zoneId="+zoneId+"&cooperativeId="+cooperativeId,
					        dataType: 'json',
					        quietMillis: 100,
					        
					        results: function (data) {
					            return {results: data};
					        }
					    }
					}).on('change', function(event){
						if(event.target == this){
							var lineId = event.val;
							$(".car-select").select2({
								placeholder: "Select car",
								minimumResultsForSearch: 10,
								ajax: {
									url: url+"?lineId="+lineId+"&cooperativeId="+cooperativeId,
							        dataType: 'json',
							        quietMillis: 100,
							        
							        results: function (data) {
							            return {results: data};
							        }
							    }
							});
						}
					});
				}
			});
			var zoneId = $(".zone-select").select2("val");
			$(".line-select").off('change');
			$(".line-select").select2({
				placeholder: "Select line",
				minimumResultsForSearch: 10,
				ajax: {
					url: url+"?zoneId="+zoneId+"&cooperativeId="+cooperativeId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data};
			        }
			    }
			}).on('change', function(event){
				if(event.target == this){
					var lineId = event.val;
					$(".car-select").select2({
						placeholder: "Select car",
						minimumResultsForSearch: 10,
						ajax: {
							url: url+"?lineId="+lineId+"&cooperativeId="+cooperativeId,
					        dataType: 'json',
					        quietMillis: 100,
					        
					        results: function (data) {
					            return {results: data};
					        }
					    }
					});
				}
			});
			var lineId = $(".line-select").select2("val");
			$(".car-select").select2({
				placeholder: "Select car",
				minimumResultsForSearch: 10,
				ajax: {
					url: url+"?lineId="+lineId+"&cooperativeId="+cooperativeId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data};
			        }
			    }
			});
		}
	});	

	var cooperativeId = $(".cooperative-select").select2("val");
	$(".zone-select").select2({
		placeholder: "Select zone",
		minimumResultsForSearch: 10,
		ajax: {
	        url: url+"?cooperativeId="+cooperativeId,
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data.zone};
	        }
	    }
	}).on('change', function(event){
		if(event.target == this){
			var zoneId = event.val;
			$(".line-select").off('change');
			$(".line-select").select2({
				placeholder: "Select line",
				minimumResultsForSearch: 10,
				ajax: {
					url: url+"?zoneId="+zoneId+"&cooperativeId="+cooperativeId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data};
			        }
			    }
			}).on('change', function(event){
				if(event.target == this){
					var lineId = event.val;
					$(".car-select").select2({
						placeholder: "Select car",
						minimumResultsForSearch: 10,
						ajax: {
							url: url+"?lineId="+lineId+"&cooperativeId="+cooperativeId,
					        dataType: 'json',
					        quietMillis: 100,
					        
					        results: function (data) {
					            return {results: data};
					        }
					    }
					});
				}
			});
		}
	});
	
	$(".line-select").select2({
		placeholder: "Select line",
		minimumResultsForSearch: 10,
		ajax: {
			url: url+"?cooperativeId="+cooperativeId,
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data.line};
	        }
	    }
	});

	$(".car-select").select2({
		placeholder: "Select car",
		minimumResultsForSearch: 10,
		ajax: {
			url: url+"?cooperativeId="+cooperativeId,
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data.car};
	        }
	    }	
	});

	
});
</script>