<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')?>
<? $this->headTitle($this->translate('Admin Cooperative'));?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Add car model'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Model added successfully.'); ?> 
</div>
<? endif;?>
<?php
$form = $this->carModelForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/cooperative/car_model_add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<? $carModel = $form->get('car-model-form'); ?>
<? echo $this->formHidden($carModel->get('id'));?>
<? $make = $carModel->get('make'); ?>
<div class="form-group <?php if($this->formElementErrors($make)) 
echo "has-error" ?>">
<?php echo $this->formLabel($make); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($make) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($make); ?>
</div>
</div>
<? $name = $carModel->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? echo $this->formHidden($form->get('csrf'));?>

<div class="fd_action pull-right">
	<?=$this->formElement($form->get('submit'));?>
</div>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')?>
			
<script type="text/javascript">
$(function() {
	$(".make-select").select2({
		minimumResultsForSearch: 10		
	});
});
</script>