<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/DT_bootstrap.css');?>
<? $this->headTitle($this->translate('Admin Cooperative'));?>
<div class="row">
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('List cooperative'); ?></h3>
</div>
<div class="panel-body">
<? $cooperatives = $this->cooperatives;?>
<div class="table-responsive">
<table id="example" class="table table-striped table-bordered dataTable">
<thead><tr><th><?=$this->translate('Name'); ?></th><th><?=$this->translate('Admin'); ?></th><th><?=$this->translate('Teller'); ?></th>
<th><?=$this->translate('Contact'); ?></th><th><?=$this->translate('Action'); ?></th></tr></thead>
<tbody>
<? foreach($cooperatives as $cooperative):
	$admins = $cooperative->getAdmins();
	$tellers = $cooperative->getTellers();	
	$adminToDisplay = '';
	foreach ($admins as $admin):
		$adminToDisplay .= ucfirst($admin->getFirstname()) . '; ';
	endforeach;
	$adminToDisplay = rtrim($adminToDisplay, '; ');
	$tellerToDisplay = '';
	foreach ($tellers as $teller):
		$tellerToDisplay .= ucfirst($teller->getFirstname()) . '; ';
	endforeach;
	$tellerToDisplay = rtrim($tellerToDisplay, '; ');
	$contacts = $cooperative->getContacts();
	$contactToDisplay = '';
	foreach ($contacts as $contact):
		$contactToDisplay .= $contact->getValue() . '-';
	endforeach;
	$contactToDisplay = rtrim($contactToDisplay, '-');
?>
<tr><td><?=ucfirst($cooperative->getName()); ?></td><td><?=$adminToDisplay; ?></td>
<td><?=$tellerToDisplay; ?></td><td><?=$contactToDisplay; ?></td>
<td><a class="btn btn-primary btn-xs" href="<?=$this->url('admin/cooperative/edit', array('lang' => $this->lang, 'cooperativeId' => $cooperative->getId()), array(), true); ?>"><?=$this->translate('Edit'); ?></a></td></tr>
<? endforeach;?>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/jquery.dataTables.min.js')
			->appendFile($this->basePath() . '/js/DT_bootstrap.js');?>