<?php echo $this->headLink()				
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/DT_bootstrap.css');?>
<div class="row">
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Line selection'); ?></h3>
</div>
<div class="panel-body">
<form class="form-horizontal" role="form" method="post" action="<?=$this->url('tools/transportation_reservation', array(), array(), true);?>">
<div class="form-group">
	<label class="col-sm-3 control-label" for="zone"><?=$this->translate('Zone'); ?></label>
	<div class="col-sm-7"><input type="hidden" class="zone-select form-control" name="zone"/></div>
</div>
<div class="form-group">
	<label class="col-sm-3 control-label" for="line"><?=$this->translate('Line'); ?></label>
	<div class="col-sm-7"><input type="hidden" class="line-select form-control" name="line"/></div>
</div>
<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<button value="" class="btn btn-primary" name="submit" type="submit"><?=$this->translate('Submit'); ?></button></div>
</div>
</form>

</div>
</div>
</div>
<? $reservationBoards = $this->reservationBoards;?>
<? if (isset($reservationBoards)):?>
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Reservation board'); ?></h3>
</div>
<div class="panel-body">

<? $locale = 'en_US';
	if ($this->lang == 'en') {
		$locale = 'en_US';
	} else if ($this->lang == 'mg' || $this->lang == 'fr') {
		$locale = 'fr_FR';
	}
?>
<div class="table-responsive">
<table id="list_reservation_board" class="table table-striped table-bordered dataTable">
<thead><tr><th><small>#&nbsp;</small></th><th><small><?=$this->translate('Cooperative'); ?></small></th><th><small><?=$this->translate('Car'); ?><small</th>
<th><small><?=$this->translate('Departure time'); ?></small></th><th><small><?=$this->translate('Seat available'); ?></small></th><th><small><?=$this->translate('Action'); ?></small></th></tr></thead>
<tbody>
<? foreach($reservationBoards as $reservationBoard):
	$cooperativeName = ucwords($reservationBoard->getCooperative()->getName());
	$line = $reservationBoard->getLine()->getLineJourney();
	$car = $reservationBoard->getCar()->getLicense();
	$car = preg_replace('/\s/', '&nbsp;', $car);
	$departureTime = ucwords($this->dateFormat(
		$reservationBoard->getDepartureTime(),
		IntlDateFormatter::LONG,
		IntlDateFormatter::SHORT,
		$locale
	));
	$reservationBoardId =$reservationBoard->getId();
	$seatAvailable = $reservationBoard->getSeatAvailable();	
?>
<tr><small><td><?=$reservationBoard->getId();?></td><td><?=$cooperativeName; ?></td><td><?=$car; ?></td><td><?=$departureTime; ?></td>
<td><?=$seatAvailable; ?></td><td><a class="btn btn-primary btn-xs" href="<?=$this->url('tools/transportation_reservation/detail', array('lang' => $this->lang, 'reservationBoardId' => $reservationBoardId)); ?>"><?=$this->translate('Detail'); ?></a></td></small></tr>
<? endforeach;?>
</tbody>
</table>
</div>
</div>
</div>
</div>
<? endif;?>
</div>
<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')
			->appendFile($this->basePath() . '/js/jquery.dataTables.min.js')
			->appendFile($this->basePath() . '/js/moment-with-langs.min.js')
			->appendFile($this->basePath() . '/js/DT_bootstrap.js');?>
<script type="text/javascript">
var url = "<?=$this->url('tools/transportation_reservation', array(), array(), true); ?>";
$(document).ready(function() {
	$('#list_reservation_board').dataTable( {
		"sDom": "<'row'<'col-md-6 col-xs-12'l><'col-md-6 col-xs-12'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
		"sPaginationType": "bootstrap",
		"oLanguage": {
			"sLengthMenu": "_MENU_ records per page"
		},
        "aoColumns": [
                      null,
                      null,
                      null,  
                      { "sType": "datetime" },                    
                      null,
                      null
                  ]
	} );
	$('#list_reservation_board_length select').addClass('form-control');
	$('#list_reservation_board_filter input').addClass('form-control');
	$('.dataTables_length').addClass('form-group');
	$('.dataTables_filter').addClass('form-group');

	$(".zone-select").select2({
		placeholder: "Select zone",
		minimumResultsForSearch: 10,
		ajax: {
	        url: url+"?type=zone",
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data};
	        }
	    }
	}).on("change", function(event){
		if(event.target == this){
			var zoneId = event.val;
			$(".line-select").select2({
				placeholder: "Select line",
				minimumResultsForSearch: 10,
				ajax: {
					url: url+"?type=line&zoneId="+zoneId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data};
			        }
			    }
			});
		}
	});
	var zoneId = $(".zone-select").select2("val");
	$(".line-select").select2({
		placeholder: "Select line",
		minimumResultsForSearch: 10,
		ajax: {
	        url: url+"?type=line&zoneId="+zoneId,
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data};
	        }
	    }
	});
	
} );
</script>