<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/blueimp-gallery.min.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.fileupload.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.fileupload-ui.css')
                ?>
<? $this->headTitle($this->translate('Admin Product'));?>
<div class="row">
<div class="col-md-9 col-md-offset-2">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Product'); ?></h3>
</div>
<div class="panel-body">
<?php
$form = $this->productForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/product/add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<?=$this->form()->openTag($form) ?>
<? $product = $form->get('product-form');?>
<?=$this->formHidden($product->get('id')); ?>

<? $shop = $product->get('shop'); ?>
<div class="form-group <?php if($this->formElementErrors($shop)) 
echo "has-error" ?>">
<?php echo $this->formLabel($shop); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($shop) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($shop); ?>
</div>
</div>

<? $type = $product->get('type'); ?>
<div class="form-group <?php if($this->formElementErrors($type)) 
echo "has-error" ?>">
<?php echo $this->formLabel($type); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($type) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($type); ?>
</div>
</div>

<? $name = $product->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? $description = $product->get('description'); ?>
<div class="form-group <?php if($this->formElementErrors($description)) 
echo "has-error" ?>">
<?php echo $this->formLabel($description); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($description) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($description); ?>
</div>
</div>

<? $price = $product->get('price'); ?>
<div class="form-group <?php if($this->formElementErrors($price)) 
echo "has-error" ?>">
<?php echo $this->formLabel($price); ?>
<div class="gdn_input_margin">
<div class="input-group">  
  <?php echo $this->formElement($price) ?>
  <span class="input-group-addon">Ariary</span>
</div>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($price); ?>
</div>
</div>

<? $measurement = $product->get('measurement'); ?>
<div class="form-group <?php if($this->formElementErrors($measurement)) 
echo "has-error" ?>">
<?php echo $this->formLabel($measurement); ?>
<div class="gdn_input_margin">
<div class="input-group"> 
<?php echo $this->formElement($measurement) ?>
<span class="input-group-addon input-grp-qty">Pi&egrave;ce</span>
</div>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($measurement); ?>    
</div>
</div>

<!--
<? //$attributesCollection = $product->get('attributes');?>
<div id="attributes-group">
	<? foreach ($attributesCollection as $c):?>	
	<div class="attributes-element">
		<? //echo $this->formHidden($c->get('product'));?>
		<div class="form-group">
			<?=$this->formLabel($c->get('attribute')); ?>
			<div class="gdn_input_margin">
			<?=$this->formElement($c->get('attribute')); ?>			
			</div>
		</div>
		<div class="form-group <?php if($this->formElementErrors($c->get('value'))) 
echo "has-error" ?>">
			<?=$this->formLabel($c->get('value')); ?>
			<div class="gdn_input_margin">
			<?=$this->formElement($c->get('value')); ?>
			<?=$this->formElementErrors()
				->setMessageOpenFormat('<div class="help-block">')
			    ->setMessageSeparatorString('</div><div class="help-block">')
			    ->setMessageCloseString('</div>')
			    ->render($c->get('value')); ?>
			</div>
		</div>
	</div>
	<? endforeach;?>
</div>

<div class="form-group">
	<span id="tplAttribute" data-template="<?=htmlspecialchars('<div class="attributes-element"><input type="hidden" value="" name="product-form[attributes][__placeholder__][id]"><div class="form-group"><label for="product-form[attributes][__placeholder__][type]" class="col-sm-3 control-label">').
	$this->translate('Attribute type').htmlspecialchars('</label><div class="gdn_input_margin"><select class="form-control" name="product-form[attributes][__placeholder__][type]"><option value="1">').
	$this->translate('mobile').htmlspecialchars('</option><option value="2">').$this->translate('mail').htmlspecialchars('</option><option value="3">').
	$this->translate('address').htmlspecialchars('</option></select></div></div><div class="form-group"><label for="product-form[attributes][__placeholder__][value]" class="col-sm-3 control-label">').
	$this->translate('Attribute value').htmlspecialchars('</label><div class="gdn_input_margin"><input type="text" value="" class="form-control" name="product-form[attributes][__placeholder__][value]"></div></div></div>') ?>"></span>
	<div class="col-sm-4 col-sm-offset-3"></div>
</div>

-->
<? echo $this->formHidden($product->get('deleted'));?>
<? echo $this->formHidden($product->get('created'));?>
<div id="attributes-group"></div>

<? echo $this->formHidden($form->get('csrf'));?>
<div class="listFileId"></div>
<div class="row">
<div class="col-sm-12">
<div class="fd_upload pull-left">
	<a href="#" class="btn btn-info show-modal" onclick="return false;"><i class="fa fa-camera"></i></a>
</div>
<div class="fd_action pull-right">
	<?=$this->formElement($form->get('submit'));?>
</div>
</div>
</div>
<?php echo $this->form()->closeTag() ?>

</div>
</div>
</div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog wide-modal">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><?=$this->translate('Upload image'); ?></h4>
      </div>
      <div class="modal-body modal-body-modified">
		<? 
      	$form = $this->fileForm;
		$form->prepare();
		$form->setAttribute('class', 'form-inline');
		echo $this->form()->openTag($form);
		$elem = $form->get('files');
		?>
		<div class="row fileupload-buttonbar">
            <div class="container media-content">
            	<div class="row row-media hide">
	            	<div class="col-md-8 image-preview-container">
	            		<div class="container ">
	            			<div class="row files"></div>		
	            		</div>
	            	</div>
					<div class="col-md-4 image-edit-container">
	            		<div class="container ">
	            			<div class="row"><div class="col-md-12"><div class="image-detail-container"></div></div></div>		
	            		</div>
	            	</div>
            	</div>
            	<div class="row row-upload">
					<div class="img-selection center-block center-vertical">
						<div class="file-upload-btn ">
							<span class="btn btn-default btn-lg  fileinput-button">
			                    <span><?=$this->translate('Add images'); ?></span>
			                    <?php echo $this->formFile($elem); ?>
							</span>
		                </div>		
		                <?=$this->translate('or'); ?>               
						<button class="btn btn-default btn-lg btn-choose"><?=$this->translate('Choose images'); ?></button>
					</div>
            	</div>
			</div>
        </div>
         <?php echo $this->form()->closeTag($form); ?>
      </div><!-- /.modal-body -->      
      
      <div class="modal-footer modal-footer-modified">
		<button class="btn btn-default btn-preview-add-image pull-left hide"><?=$this->translate('Add images'); ?></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('Close'); ?></button>
        <button type="button" id="save-images" class="btn btn-primary" disabled="disabled"><?=$this->translate('Insert into post'); ?></button>
      </div><!-- /.modal-footer -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
<div class="col-md-4 template-upload fade">
{% if (i) { %}
	<span class="preview">
       	{% if (file.thumbnailUrl) { %}
           	<a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
    	{% } %}
		
	</span>
{% } else { %}
	<div class="my-progress fileupload-progress fade">
		<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
			<div class="progress-bar progress-bar-success" style="width:0%;"></div>
		</div>
	</div>
	<strong class="error text-danger"></strong>
	<button class="btn btn-warning cancel">
    	<i class="glyphicon glyphicon-ban-circle"></i>
        <span>Cancel</span>
	</button>
{% } %}
</div>
{% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
{% if (file.thumbnailUrl) { %}
	<div class="col-md-4 template-download fade">
		<span class="preview">		
			<img src="{%=file.thumbnailUrl%}" class="img-thumbnail img-thumbnail-preview">
			<span class="my-zoom-icon">
				<a href='#' data-toggle="tooltip" title="Deselect" class="deselect my-tooltip"><span class="glyphicon glyphicon-minus"></span></a> 
				<a href="#" data-toggle="tooltip" title="Crop" class="crop my-tooltip"><span class="glyphicon glyphicon-th"></span></a> 
				<a href="#" class="delete my-tooltip"  data-toggle="tooltip" title="Delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}><span class="glyphicon glyphicon-remove"></span></a>
			</span>
			<input type="hidden" class="fileId" value="{%=file.id%}"/>		
		
			<input type="checkbox" name="delete" value="1" class="toggle hidden">
		</span>	
	</div>
{% } %}
{% if (file.error) { %}
	<div class="col-md-4 template-download fade">
    	<div class="error-file"><span class="label label-danger">Error</span> {%=file.error%}</div>
	</div>
		{% } %}
{% } %}
</script>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')
			->appendFile($this->basePath() . '/js/vendor/jquery.ui.widget.js')
			->appendFile($this->basePath() . '/js/jquery.godana.js')
            ->appendFile($this->basePath() . '/js/tmpl.min.js')
            ->appendFile($this->basePath() . '/js/load-image.min.js')
            ->appendFile($this->basePath() . '/js/canvas-to-blob.min.js')
            ->appendFile($this->basePath() . '/js/jquery.blueimp-gallery.min.js')
            ->appendFile($this->basePath() . '/js/jquery.iframe-transport.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-process.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-video.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-ui.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-validate.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-image.js')
            ->appendFile($this->basePath() . '/js/jquery.fileupload-audio.js');?>
<script type="text/javascript">
var shop_placeholder = "<?=$this->translate('Select shop'); ?>";
var type_placeholder = "<?=$this->translate('Select type'); ?>";
var ajax_url = "<?=$this->url('admin/product/upload', array(), array(), true); ?>",
	url_attribute = "<?=$this->url('admin/product/list_attribute', array(), array(), true); ?>";
$(function() {
	$(".shop-select").select2({ 
		placeholder: shop_placeholder,
		minimumResultsForSearch: 10
	}).on('change', function(event){
		if(event.target == this){
			var shopId = event.val;
			$("#myModal").find(".row.files").html("");
			$('.show-modal').off("click");
			if (shopId != "") {
				$('.show-modal').godana({
					off: false,
					doCrop: false,
					ajaxUrl:ajax_url+'?shopId='+shopId,
				});
			} else {
				$('.show-modal').click(function(e) {			
					alert(shop_placeholder);
					return false;
				});		
			}
		}
	});
	var shopId = $(".shop-select").select2("val");
	$('.show-modal').off("click");
	if (shopId != "") {			
		$('.show-modal').godana({
			doCrop: false,
			ajaxUrl: ajax_url+'?shopId='+shopId,
		});
	} else {
		$('.show-modal').click(function(e) {			
			alert(shop_placeholder);
			return false;
		});		
	}
	$('#save-images').click(function(e) {
		$('.fileId').each(function() {
			if ($(this).hasClass('file-selected')) {				
	   			$('.listFileId').append('<input type="hidden" name="file-id[]" class="file-id" value="'+$(this).val()+'">');
			}   		
		});
		$('#myModal').modal('hide');		
		return false;
	});

	$(".product-type-select").select2({
		placeholder: type_placeholder,
		minimumResultsForSearch: 10
	}).on('change', function(event){
		if(event.target == this){
			var typeId = event.val;
			$.ajax({
				url: url_attribute,
				data: "productType="+typeId,
				dataType: "json",
				success: function(data) {
					var unit = data.unit;
					var form_groups = data.form_group;
					if (unit != undefined) {
						$('.input-grp-qty').html(unit);
					}
					$('#attributes-group').html("");
					if (form_groups != undefined && form_groups.length > 0) {
						for (var i = 0; i < form_groups.length; i++) {
							var form_group = form_groups[i];
							$('#attributes-group').append($(form_group));
						}
					} else {
						$('#attributes-group').html("");
					}
				}
			});
		}
	});

	var typeId = $(".product-type-select").select2("val");
	if (typeId != "") {
		$.ajax({
			url: url_attribute,
			data: "productType="+typeId,
			dataType: "json",
			success: function(data) {
				var unit = data.unit;
				var form_groups = data.form_group;
				if (unit != undefined) {
					$('.input-grp-qty').html(unit);
				}
				$('#attributes-group').html("");
				if (form_groups != undefined && form_groups.length > 0) {
					for (var i = 0; i < form_groups.length; i++) {
						var form_group = form_groups[i];
						$('#attributes-group').append($(form_group));
					}
				} else {
					$('#attributes-group').html("");
				}
			}
		});
	}

//	$(".chosen-select.product-type-select").on('liszt:ready', function(e, chosen) {
//		var idType = e.currentTarget.value;
//		$.ajax({
//			url: "list-attribute?productType="+idType,
//    		type: "POST",
//    		cache: false,
//    		dataType: "json",
//    		beforeSend: function() {					
//    		},
//            success: function(data) {
//	            var unit = data.unit;
//	            $('.input-grp-qty').html(unit);
//	            var attributes = data.attribute;
//            	$('#attributes-group').html('');
//	            for (i = 0; i < attributes.length; i++) {				            
//		            var id = attributes[i].id;
//		            var name = attributes[i].name;
//		            addAttrElem(i, id, name);
//	            }
//	        }
//		});
//	}).chosen({ 
//		width: '100%',
//		disable_search_threshold: 10,
//	}).change(function(event, params){
//		if(event.target == this){
//			var idType = params.selected;
//			$.ajax({
//				url: "list-attribute?productType="+idType,
//	    		type: "POST",
//	    		cache: false,
//	    		dataType: "json",
//	    		beforeSend: function() {					
//	    		},
//	    		success: function(data) {
//		            var unit = data.unit;
//		            $('.input-grp-qty').html(unit);
//		            var attributes = data.attribute;
//	            	$('#attributes-group').html('');
//		            for (i = 0; i < attributes.length; i++) {				            
//			            var id = attributes[i].id;
//			            var name = attributes[i].name;
//			            addAttrElem(i, id, name);
//		            }
//		        }
//			});
//		}
//	});

	var addAttrElem = function(index, id, label) {
		var attributeElem = '<div class="attributes-element">';
		attributeElem += '<input type="hidden" name="attributes['+index+'][id]" value="'+id+'">';
		attributeElem += '<div class="form-group">';
		attributeElem += '<label class="col-sm-3 control-label" for="attributes['+index+'][value]">'+label+'</label>';
		attributeElem += '<div class="gdn_input_margin">';
		attributeElem += '<input class="form-control" type="text" name="attributes['+index+'][value]">';
		attributeElem += '</div></div></div>';
		$('#attributes-group').append(attributeElem);
	}
	
});
</script>

<!-- The blueimp Gallery widget -->
        <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter="">
		    <div class="slides"></div>
		    <h3 class="title"></h3>
		    <a class="prev">‹</a>
		    <a class="next">›</a>
		    <a class="close">×</a>
		    <a class="play-pause"></a>
		    <ol class="indicator"></ol>
		</div>