<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/DT_bootstrap.css');?>
<? $this->headTitle($this->translate('Admin Product'));?>
<div class="row">
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?=$this->translate('List product'); ?></h3>
</div>
<div class="panel-body">
<? $products = $this->products;?>
<div class="table-responsive">
<table id="example" class="table table-striped table-bordered dataTable">
<thead><tr><th><?=$this->translate('Shop'); ?></th><th><?=$this->translate('Name'); ?></th>
<th><?=$this->translate('Type'); ?></th></tr></thead>
<tbody>
<? foreach($products as $product):?>
<? $shop_name = $product->getShop()->getName();?>
<? $product_name = $product->getName();?>
<? $product_type = $product->getType()->getName();?>
<tr><td><?=ucfirst($shop_name); ?></td><td><?=ucfirst($product_name); ?></td>
<td><?=ucfirst($product_type); ?></td></tr>
<? endforeach;?>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/jquery.dataTables.min.js')
			->appendFile($this->basePath() . '/js/DT_bootstrap.js');?>