<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/DT_bootstrap.css');?>
<? $this->headTitle($this->translate('Admin Product'));?>
<div class="row">
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?=$this->translate('List product type'); ?></h3>
</div>
<div class="panel-body">
<? $productTypes = $this->productTypes;?>
<div class="table-responsive">
<table id="example" class="table table-striped table-bordered dataTable">
<thead><tr><th><?=$this->translate('Name'); ?></th><th><?=$this->translate('Unit'); ?></th>
<th><?=$this->translate('Attributes'); ?></th></tr></thead>
<tbody>
<? foreach($productTypes as $productType):?>
<? $attributes = $productType->getAttributes();?>
<? $attributeToDisplay = '';?>
<? foreach ($attributes as $attribute):?>
<? $attributeToDisplay .= '<span class="label label-info">' . $attribute->getName() . '</span> ';?>
<? endforeach;?>
<? $attributeToDisplay = rtrim($attributeToDisplay, ' ');?>
<tr><td><?=ucfirst($productType->getName()); ?></td><td><?=ucfirst($productType->getUnit()); ?></td>
<td><?=$attributeToDisplay; ?></td></tr>
<? endforeach;?>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/jquery.dataTables.min.js')
			->appendFile($this->basePath() . '/js/DT_bootstrap.js');?>