<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/typeahead.js-bootstrap.css')
                ?>
<? $this->headTitle($this->translate('Admin Product'));?>
<div class="row">
<div class="col-md-8 col-md-offset-2">
<div class="panel panel-primary">
<div class="panel-heading"><h3 class="panel-title"><?=$this->translate('Create product type'); ?></h3></div>
<div class="panel-body">
<?php
$form = $this->productTypeForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/product/type_add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<?=$this->form()->openTag($form) ?>
<? $productType = $form->get('product-type-form'); ?>
<?=$this->formHidden($productType->get('id'));?>

<? $name = $productType->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? $unit = $productType->get('unit'); ?>
<div class="form-group <?php if($this->formElementErrors($unit)) 
echo "has-error" ?>">
<?php echo $this->formLabel($unit); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($unit) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($unit); ?>
</div>
</div>

<? $attribute = $productType->get('attribute'); ?>
<div class="form-group <?php if($this->formElementErrors($attribute)) 
echo "has-error" ?>">
<?php echo $this->formLabel($attribute); ?>
<div class="gdn_input_margin">
<?php echo $this->formElement($attribute) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($attribute); 
	?>
</div>
</div>


<? echo $this->formHidden($form->get('csrf'));?>

<div class="row">
<div class="col-sm-12">
<div class="fd_action pull-right">
	<?=$this->formElement($form->get('submit'));?>
</div>
</div>
</div>
<?php echo $this->form()->closeTag() ?>

</div>
</div>
</div>
</div>   

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/typeahead.min.js')
			->appendFile($this->basePath() . '/js/select2.min.js')
			->appendFile($this->basePath() . '/js/vendor/jquery.ui.widget.js');?>

<script type="text/javascript">
var attribute_placeholder = "<?=$this->translate('Attributes'); ?>";
var url_attribute = "<?=$this->url('admin/product/ajax_list_attribute', array(), array(), true); ?>";
$(function() {
	var opts = {
		placeholder: attribute_placeholder,
		tags: true,
		minimumResultsForSearch: 4,
		tokenSeparators: [",", " "],
		createSearchChoice: function(term, data) {
			if ($(data).filter(function() {
		    	return this.text.localeCompare(term) === 0;
		    }).length === 0) {
		    	return {
		        	id: term,
		        	text: term
		      	};
		    }
		},
		multiple: true,
		ajax: {
			url: url_attribute,
		    dataType: "json",
		    data: function(term, page) {
		    	return {
		        	q: term
		      	};
		    },
		    results: function(data, page) {
		    	return {
		        	results: data
		      	};
		    }
		}	
	};
	$(".attribute-select").data("s2opts", opts).select2(opts);
});
</script>