<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/fonts/SansationBold/font.css')
                ->appendStylesheet($this->basePath() . '/fonts/SansationRegular/font.css')?>
<? $this->headTitle($this->translate('Shops'));?>
<? $shop = $this->shop;?>
<? 
	$user = $shop->getOwner();
	$cover = $shop->getCover();
	$coverExist = false;
	if (isset($cover) && $cover instanceof \Godana\Entity\File) {
		$coverExist = true;
		$coverUrl = $shop->getCover()->getImageRelativePathByDimension('md');
	}
	$categories = $shop->getCategories();
	$categoryToDisplay = '';
	foreach ($categories as $category):
		$categoryToDisplay .= '<a class="btn btn-success btn-lg" href="'.$this->url('shop', array('categoryIdent' => $category->getIdent()), array(), true).'">' . $category->getName() . '</a>' . ' ';
	endforeach;
	$categoryToDisplay = rtrim($categoryToDisplay, ' ');
?>
<?  $this->plugin("currencyformat")->setCurrencyCode("MGA")->setLocale("fr_FR");?>
<? if ($coverExist):?>
<div class="coverPhoto" style="background: url(<?=$coverUrl ?>) no-repeat center #CCCCCC">
<!--  <div class="owner-photo"><img src="<?=$this->userPicture('md', $user); ?>" class="img-thumbnail"/></div>-->
<div class="center-block cover-title">
<div class="panel panel-default">
	<div class="panel-body text-center">
    	<h3 class="shop-name fontsforweb_fontid_425"><?=$shop->getName(); ?></h3>
    	<hr/>
    	<p class="fontsforweb_fontid_424"><?=$shop->getDescription(); ?></p>
	</div>
</div>
</div>
</div>


<? else:?>
<div class="jumbotron">
<h1><?=$shop->getName(); ?></h1>
<p><?=$shop->getDescription(); ?></p>
<h5><?=$categoryToDisplay; ?></h5>
</div>
<? endif;?>
<? $products = $shop->getProducts();?>
<div class="row">
<? $count = 0;?>
<? foreach ($products as $product):?>
<? $count++;?>
<? $productType = $product->getType();?>
<div class="col-md-4 col-sm-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?=$product->getName(); ?>
			<a class="btn btn-default pull-right btn-xs" href="<?=$this->url('detail-product', array('lang' => $this->lang, 'shopIdent' => $shop->getIdent(), 'productId' => $product->getId())); ?>"><?=$this->translate('More'); ?> <i class="glyphicon glyphicon-chevron-right"></i></a></h3>
		</div>
		<div class="panel-body">
			<p><?=$product->getDescription(); ?></p>
			<? $files = $product->getFiles();?>
			<? $productId = $product->getId(); ?>
			<? if (isset($files) && count($files) > 0):?>
				<div class="row well well-sm" id="<?=$productId; ?>">
				<? foreach ($files as $file):?>	
					  <div class="col-xs-6 col-sm-4 col-md-4" >					  
					    <a href="<?=$file->getUrl(); ?>" class="img-thumbnail"  download="<?=$file->getName(); ?>" data-gallery="#blueimp-gallery-<?=$productId; ?>">
					      <img src="<?=$file->getThumbnailUrl(); ?>" class="img-responsive">
					    </a>
					  </div>					  					  									
				<? endforeach;?>
				</div>
			<? endif;?>
			<h4 class="bid-info">
			<a href="#" class="btn btn-success btn-xs"><?=$productType->getName(); ?></a>&nbsp;
			<span class="label label-danger"><?=$this->currencyFormat($product->getPrice()); ?> / <?=$product->getMeasurement();?> <?=$productType->getUnit(); ?></span>
			<? $productAttributes = $product->getAttributes();?>
			<? if (isset($productAttributes) && count($productAttributes) > 0):?>
			<? foreach ($productAttributes as $productAttr):?>
				<? $attr = $productAttr->getAttribute(); ?>
				<? $attrName = $attr->getName();?>
				<? $attrValue = $productAttr->getValue();?>
				<span class="label label-primary"><?=$attrName; ?>: <?=$attrValue; ?></span>
			<? endforeach;?>
			<? endif;?>
			</h4>
		</div>		
	</div>
</div>
<? if ($count % 3 == 0):?>
<div class="clearfix visible-md"></div>
<? elseif ($count % 2 == 0):?>
<div class="clearfix visible-sm"></div>
<? endif;?>
<? endforeach;?>
</div>