<div class="main-content">
	<div class="row-fluid">
		<div class="span12">
			<div class="login-container">
				<div class="row-fluid">
					<div class="center block">
						<a href="<?=$this->url('home', array(), array(), true) ?>"><img id="logo-header" src="<?php echo $this->basePath();?>/assets/img/logo-godana2.png" alt="Logo"/></a>
					</div>
				</div>

				<div class="space-6"></div>

				<div class="row-fluid">
					<div class="position-relative">
						<?php if (!$isUser): ?>
						<div class="alert alert-danger"><h5><?=$this->translate(sprintf('The username <strong>%s</strong> does not exist!', $this->username)); ?></h5></div>
						<?php elseif ($isUserActivated): ?>
						<div class="alert alert-danger"><h5><?=$this->translate('This account is already activated!'); ?></h5></div>
						<?php else: ?>
						<div class="alert alert-info"><h5><?=$this->translate('Thank you for joining Godana! An email has been sent to your mailbox. Please click the link to activate your account.'); ?></h5></div>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
