<?php echo $this->headLink()
				->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/datepicker3.css');?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Add user'); ?></h3>
</div>
<div class="panel-body">
<?php
$form = $this->addUserForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/user/add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
	<?php foreach ($form as $element): ?>
		<div class="form-group <?php if($this->formElementErrors($element)) 
                                echo "has-error" ?>">
		<?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formLabel($element); ?>
        <?php endif; ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <div class="col-sm-4 col-sm-offset-4">
            <?php echo $this->formButton($element) ?></div>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <div class="col-sm-5"><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>
        <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
        	<div class="col-sm-5">
        		<?php echo $this->formSelect($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
        	</div>       
        <?php else: ?>
            <div class="col-sm-5">
            	<?php echo $this->formInput($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
            </div>
        <?php endif ?>
        </div>
	<?php endforeach; ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>
<?php $this->inlineScript()
	->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
	->appendFile($this->basePath() . '/js/select2.min.js');
?>
<script type="text/javascript">
$(function() {
	$(".datepicker").datepicker();
	$(".chosen-select").select2({
		minimumResultsForSearch: 10,
	});
});
</script>