<? $this->headTitle($this->translate('User'));?>
<? $locale = 'en_US';
	if ($this->lang == 'en') {
		$locale = 'en_US';
	} else if ($this->lang == 'mg' || $this->lang == 'fr') {
		$locale = 'fr_FR';
	}
?>
<div class="breadcrumbs" id="breadcrumbs">
	<ul class="breadcrumb">
		<li>
			<i class="icon-home home-icon"></i>
			<a href="#">Home</a>

			<span class="divider">
				<i class="icon-angle-right arrow-icon"></i>
			</span>
		</li>

		<li>
			<a href="#">More Pages</a>

			<span class="divider">
				<i class="icon-angle-right arrow-icon"></i>
			</span>
		</li>
		<li class="active">User Profile</li>
	</ul><!--.breadcrumb-->

	<div class="nav-search" id="nav-search">
		<form class="form-search" />
			<span class="input-icon">
				<input type="text" placeholder="Search ..." class="input-small nav-search-input" id="nav-search-input" autocomplete="off" />
				<i class="icon-search nav-search-icon"></i>
			</span>
		</form>
	</div><!--#nav-search-->
</div><!--/.breadcrumbs  -->

<div class="page-content">
	<div class="page-header position-relative">
		<h1>
			User Profile Page
			<small>
				<i class="icon-double-angle-right"></i>
				3 styles with inline editable feature
			</small>
		</h1>
	</div><!--/.page-header-->

	<div class="row-fluid">
		<div class="span12">
			<!--PAGE CONTENT BEGINS-->
			<div>
				<div id="user-profile-view" class="user-profile row-fluid">
					<div class="tabbable">
						<ul class="nav nav-tabs padding-18 padding-right-18">
							<li class="active">
								<a data-toggle="tab" href="#home">
									<i class="green icon-user bigger-120"></i>
									Profile
								</a>
							</li>

							<li>
								<a data-toggle="tab" href="#feed">
									<i class="orange icon-rss bigger-120"></i>
									Activity Feed
								</a>
							</li>

							<li>
								<a data-toggle="tab" href="#pictures">
									<i class="pink icon-picture bigger-120"></i>
									Pictures
								</a>
							</li>
							
							<li class="pull-right">
								<a href="#" class="edit-profile">
									<i class="red icon-edit bigger-120"></i>
									Profile
								</a>
							</li>
							
						</ul>

						<div class="tab-content no-border padding-24">
							<div id="home" class="tab-pane in active">
								<div class="row-fluid">
									<div class="span3 center">
										<span class="profile-picture">
											<img class="" id="avatar2" src="<?php echo $this->userPicture('md'); ?>" alt="<?php echo $this->zfcUserDisplayName() ?>" />
										</span>
										<div class="space space-4"></div>
									</div><!--/span-->

									<div class="span9">		
										<div class="profile-user-info profile-user-info-striped">
											<div class="profile-info-row">
												<div class="profile-info-name"><?php echo $this->translate('Username')?>  </div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getUsername(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> <?php echo $this->translate('Name')?> </div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getFirstname(); ?></span>
													<span><?php echo $this->zfcUserIdentity()->getLastname(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Age </div>

												<div class="profile-info-value">
													<span><?php echo $this->userAge(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Joined </div>
												<?php $joined = $this->dateFormat(
													$this->zfcUserIdentity()->getRegisterTime(),
													IntlDateFormatter::MEDIUM,
													IntlDateFormatter::NONE,
													$locale
												); ?>
												<div class="profile-info-value">
													<span><?php echo $joined; ?></span>
												</div>
											</div>
											
											<div class="profile-info-row">
												<div class="profile-info-name"> Email </div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getEmail(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name">
													Gender
												</div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getSex() ? $this->zfcUserIdentity()->getSex() : '-'; ?></span>
												</div>
											</div>

											
										</div>
									</div><!--/span-->
								</div><!--/row-fluid-->

								
							</div><!--#home-->

							<div id="feed" class="tab-pane">
								<div class="profile-feed row-fluid">
									<div class="span6">
										
									</div><!--/span-->

									<div class="span6">
										
									</div><!--/span-->
								</div><!--/row-->

								<div class="space-12"></div>

								<div class="center">
									
								</div>
							</div><!--/#feed-->							

							<div id="pictures" class="tab-pane">
								
							</div><!--/#pictures-->
						</div>
					</div>
				</div>
			</div>
			
			<div class="hide">
				<div id="user-profile-edit" class="user-profile row-fluid">
					<div class="offset1 span10">					

						<div class="space"></div>

						<form class="form-horizontal" />
							<div class="tabbable">
								<ul class="nav nav-tabs padding-16 padding-right-16">
									<li class="active">
										<a data-toggle="tab" href="#edit-basic">
											<i class="green icon-edit bigger-125"></i>
											Basic Info
										</a>
									</li>

									<li>
										<a data-toggle="tab" href="#edit-settings">
											<i class="purple icon-cog bigger-125"></i>
											Settings
										</a>
									</li>

									<li>
										<a data-toggle="tab" href="#edit-password">
											<i class="blue icon-key bigger-125"></i>
											Password
										</a>
									</li>
									
									<li class="pull-right">
										<a href="#" class="view-profile">
											<i class="blue icon-eye-open bigger-125"></i>
											Profile
										</a>
									</li>
								</ul>

								<div class="tab-content profile-edit-tab-content">
									<div id="edit-basic" class="tab-pane in active">
										<h4 class="header blue bolder smaller">General</h4>

										<div class="row-fluid">
											<div class="span4">												
												<span class="profile-picture">
													<img class="editable" id="avatar2" src="<?php echo $this->userPicture('md'); ?>" alt="<?php echo $this->zfcUserDisplayName() ?>" />
												</span>
											</div>

											<div class="vspace"></div>

											<div class="span8">
												<div class="control-group">
													<label class="control-label" for="form-field-username">Username</label>

													<div class="controls">
														<input type="text" id="form-field-username" placeholder="Username" value="alexdoe" />
													</div>
												</div>

												<div class="control-group">
													<label class="control-label" for="form-field-first">Name</label>

													<div class="controls">
														<input class="input-small" type="text" id="form-field-first" placeholder="First Name" value="Alex" />
														<input class="input-small" type="text" id="form-field-last" placeholder="Last Name" value="Doe" />
													</div>
												</div>
											</div>
										</div>

										<hr />
										<div class="control-group">
											<label class="control-label" for="form-field-date">Birth Date</label>

											<div class="controls">
												<div class="input-append">
													<input class="input-small date-picker" id="form-field-date" type="text" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
													<span class="add-on">
														<i class="icon-calendar"></i>
													</span>
												</div>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label">Gender</label>

											<div class="controls">
												<div class="space-2"></div>

												<label class="inline">
													<input name="form-field-radio" type="radio" />
													<span class="lbl"> Male</span>
												</label>

												&nbsp; &nbsp; &nbsp;
												<label class="inline">
													<input name="form-field-radio" type="radio" />
													<span class="lbl"> Female</span>
												</label>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-comment">Comment</label>

											<div class="controls">
												<textarea id="form-field-comment"></textarea>
											</div>
										</div>

										<div class="space"></div>
										<h4 class="header blue bolder smaller">Contact</h4>

										<div class="control-group">
											<label class="control-label" for="form-field-email">Email</label>

											<div class="controls">
												<span class="input-icon input-icon-right">
													<input type="email" id="form-field-email" value="alexdoe@gmail.com" />
													<i class="icon-envelope"></i>
												</span>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-website">Website</label>

											<div class="controls">
												<span class="input-icon input-icon-right">
													<input type="url" id="form-field-website" value="http://www.alexdoe.com/" />
													<i class="icon-globe"></i>
												</span>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-phone">Phone</label>

											<div class="controls">
												<span class="input-icon input-icon-right">
													<input class="input-medium input-mask-phone" type="text" id="form-field-phone" />
													<i class="icon-phone icon-flip-horizontal"></i>
												</span>
											</div>
										</div>

										<div class="space"></div>
										<h4 class="header blue bolder smaller">Social</h4>

										<div class="control-group">
											<label class="control-label" for="form-field-facebook">Facebook</label>

											<div class="controls">
												<span class="input-icon">
													<input type="text" value="facebook_alexdoe" id="form-field-facebook" />
													<i class="icon-facebook"></i>
												</span>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-twitter">Twitter</label>

											<div class="controls">
												<span class="input-icon">
													<input type="text" value="twitter_alexdoe" id="form-field-twitter" />
													<i class="icon-twitter"></i>
												</span>
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-gplus">Google+</label>

											<div class="controls">
												<span class="input-icon">
													<input type="text" value="google_alexdoe" id="form-field-gplus" />
													<i class="icon-google-plus"></i>
												</span>
											</div>
										</div>
									</div>

									<div id="edit-settings" class="tab-pane">
										<div class="space-10"></div>

										<div>
											<label class="inline">
												<input type="checkbox" name="form-field-checkbox" />
												<span class="lbl"> Make my profile public</span>
											</label>
										</div>

										<div class="space-8"></div>

										<div>
											<label class="inline">
												<input type="checkbox" name="form-field-checkbox" />
												<span class="lbl"> Email me new updates</span>
											</label>
										</div>

										<div class="space-8"></div>

										<div>
											<label class="inline">
												<input type="checkbox" name="form-field-checkbox" />
												<span class="lbl"> Keep a history of my conversations</span>
											</label>

											<label class="inline">
												<span class="space-2 block"></span>

												for
												<input type="text" class="input-mini" maxlength="3" />
												days
											</label>
										</div>
									</div>

									<div id="edit-password" class="tab-pane">
										<div class="space-10"></div>

										<div class="control-group">
											<label class="control-label" for="form-field-pass1">New Password</label>

											<div class="controls">
												<input type="password" id="form-field-pass1" />
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-pass2">Confirm Password</label>

											<div class="controls">
												<input type="password" id="form-field-pass2" />
											</div>
										</div>
									</div>
								</div>
							</div>

							<div class="form-actions">
								<button class="btn btn-info" type="button">
									<i class="icon-ok bigger-110"></i>
									Save
								</button>

								&nbsp; &nbsp; &nbsp;
								<button class="btn" type="reset">
									<i class="icon-undo bigger-110"></i>
									Reset
								</button>
							</div>
						</form>
					</div><!--/span-->
				</div><!--/user-profile-->
			</div>
			<!--PAGE CONTENT ENDS-->
		</div><!--/.span12  -->
	</div><!--/.row-fluid  -->
</div><!--/.page-content  -->

<script type="text/javascript">
$(function() {
	$('.edit-profile').on('click', function(e){
		$('.user-profile').parent().hide();
		$('#user-profile-edit').parent().show();
	});
	$('.view-profile').on('click', function(e){
		$('.user-profile').parent().hide();
		$('#user-profile-view').parent().show();
	});
});
</script>