<?php echo $this->headLink()
				->appendStylesheet($this->basePath() . '/assets/plugins/file-upload/css/file-upload.css')
				->appendStylesheet($this->basePath() . '/assets/plugins/file-upload/css/jquery.fileupload.css')
                ->appendStylesheet($this->basePath() . '/assets/plugins/file-upload/css/jquery.fileupload-ui.css')
                ->appendStylesheet($this->basePath() . '/assets/plugins/file-upload/css/jquery.Jcrop.css')
                ->appendStylesheet($this->basePath() . '/assets/plugins/datepicker/css/datepicker3.css');?>
<? $this->headTitle($this->translate('User'));?>
<? $locale = 'en_US';
	if ($this->lang == 'en') {
		$locale = 'en_US';
	} else if ($this->lang == 'mg' || $this->lang == 'fr') {
		$locale = 'fr_FR';
	}
?>

<div class="breadcrumbs" id="breadcrumbs">
	<ul class="breadcrumb">
		<li>
			<i class="icon-home home-icon"></i>
			<a href="#">Home</a>

			<span class="divider">
				<i class="icon-angle-right arrow-icon"></i>
			</span>
		</li>

		<li>
			<a href="#">More Pages</a>

			<span class="divider">
				<i class="icon-angle-right arrow-icon"></i>
			</span>
		</li>
		<li class="active">User Profile</li>
	</ul><!--.breadcrumb-->

	<div class="nav-search" id="nav-search">
		<form class="form-search" />
			<span class="input-icon">
				<input type="text" placeholder="Search ..." class="input-small nav-search-input" id="nav-search-input" autocomplete="off" />
				<i class="icon-search nav-search-icon"></i>
			</span>
		</form>
	</div><!--#nav-search-->
</div><!--/.breadcrumbs  -->

<div class="page-content">
	<div class="page-header position-relative">
		<h1>
			User Profile Page
			<small>
				<i class="icon-double-angle-right"></i>
				3 styles with inline editable feature
			</small>
		</h1>
	</div><!--/.page-header-->

	<div class="row-fluid">
		<div class="span12">
			<!--PAGE CONTENT BEGINS-->
			<div>
				<div id="user-profile-view" class="user-profile row-fluid">
					<div class="tabbable">
						<ul class="nav nav-tabs padding-18 padding-right-18">
							<li class="active">
								<a data-toggle="tab" href="#home">
									<i class="green icon-user bigger-120"></i>
									Profile
								</a>
							</li>

							<li>
								<a data-toggle="tab" href="#feed">
									<i class="orange icon-rss bigger-120"></i>
									Activity Feed
								</a>
							</li>

							<li>
								<a data-toggle="tab" href="#pictures">
									<i class="pink icon-picture bigger-120"></i>
									Pictures
								</a>
							</li>
							
							<li class="pull-right">
								<a href="#" class="edit-profile">
									<i class="red icon-edit bigger-120"></i>
									Profile
								</a>
							</li>
							
						</ul>

						<div class="tab-content no-border padding-24">
							<div id="home" class="tab-pane in active">
								<div class="row-fluid">
									<div class="span3 center">
										<span class="profile-picture">
											<img class="" id="avatar2" src="<?php  ?>" alt="<?php echo $this->zfcUserDisplayName() ?>" />
										</span>
										<div class="space space-4"></div>
									</div><!--/span-->

									<div class="span9">		
										<div class="profile-user-info profile-user-info-striped">
											<div class="profile-info-row">
												<div class="profile-info-name"><?php echo $this->translate('Username')?>  </div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getUsername(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> <?php echo $this->translate('Name')?> </div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getFirstname(); ?></span>
													<span><?php echo $this->zfcUserIdentity()->getLastname(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Age </div>

												<div class="profile-info-value">
													<span><?php echo $this->userAge(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name"> Joined </div>
												<?php $joined = $this->dateFormat(
													$this->zfcUserIdentity()->getRegisterTime(),
													IntlDateFormatter::MEDIUM,
													IntlDateFormatter::NONE,
													$locale
												); ?>
												<div class="profile-info-value">
													<span><?php echo $joined; ?></span>
												</div>
											</div>
											
											<div class="profile-info-row">
												<div class="profile-info-name"> Email </div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getEmail(); ?></span>
												</div>
											</div>

											<div class="profile-info-row">
												<div class="profile-info-name">
													Gender
												</div>

												<div class="profile-info-value">
													<span><?php echo $this->zfcUserIdentity()->getSex() ? $this->zfcUserIdentity()->getSex() : '-'; ?></span>
												</div>
											</div>

											
										</div>
									</div><!--/span-->
								</div><!--/row-fluid-->

								
							</div><!--#home-->

							<div id="feed" class="tab-pane">
								<div class="profile-feed row-fluid">
									<div class="span6">
										
									</div><!--/span-->

									<div class="span6">
										
									</div><!--/span-->
								</div><!--/row-->

								<div class="space-12"></div>

								<div class="center">
									
								</div>
							</div><!--/#feed-->							

							<div id="pictures" class="tab-pane">
								
							</div><!--/#pictures-->
						</div>
					</div>
				</div>
			</div>
			
			<div class="hide">
				<div id="user-profile-edit" class="user-profile row-fluid">
					<div class="offset1 span10">					

						<div class="space"></div>
<?php
	$profileForm = $this->profileForm;
	$profileForm->prepare();
	$profileForm->setAttribute('class', 'form-horizontal');
	$profileForm->setAttribute('method', 'post');
	$profileForm->setAttribute('id', 'profileForm');

 ?>
						<!-- <form class="form-horizontal" >-->
							<div class="tabbable">
								<ul class="nav nav-tabs padding-16 padding-right-16">
									<li class="active">
										<a data-toggle="tab" href="#edit-basic">
											<i class="green icon-edit bigger-125"></i>
											Basic Info
										</a>
									</li>

									<li>
										<a data-toggle="tab" href="#edit-settings">
											<i class="purple icon-cog bigger-125"></i>
											Settings
										</a>
									</li>

									<li>
										<a data-toggle="tab" href="#edit-password">
											<i class="blue icon-key bigger-125"></i>
											Password
										</a>
									</li>
									
									<li class="pull-right">
										<a href="#" class="view-profile">
											<i class="blue icon-eye-open bigger-125"></i>
											Profile
										</a>
									</li>
								</ul>

								<div class="tab-content profile-edit-tab-content">
									<div id="edit-basic" class="tab-pane in active">
									 <?php echo $this->form()->openTag($profileForm) ?>
									 <div class="my-alert"></div>
										<h4 class="header blue bolder smaller">General</h4>

										<div class="row-fluid">
											<div class="span2">	
												<a href="#" class="fileinput-button show-modal">											
													<span class="profile-picture img-preview">
<!--														<img id="avatar2" src="--><?php //echo $this->userPicture('md'); ?><!--" alt="--><?php //echo $this->zfcUserDisplayName() ?><!--" />-->
													</span>
												</a>
											</div>

											<div class="vspace"></div>

											<div class="span10">
												<div class="control-group">
													<?php echo $this->formLabel($profileForm->get('username')); ?>
													<!-- <label class="control-label" for="form-field-username">Username</label>-->

													<div class="controls">														
														<?php echo $this->formInput($profileForm->get('username')) ?>
														<!-- <input type="text" id="form-field-username" placeholder="Username" value="alexdoe" />-->
													</div>
												</div>

												<div class="control-group">
													<label class="control-label" for="form-field-first">Name</label>

													<div class="controls">
														<?php echo $this->formInput($profileForm->get('firstname')) ?>
														<?php echo $this->formInput($profileForm->get('lastname')) ?>
														<!-- <input class="input-small" type="text" id="form-field-first" placeholder="First Name" value="Alex" />
														<input class="input-small" type="text" id="form-field-last" placeholder="Last Name" value="Doe" />-->
													</div>
												</div>
											</div>
										</div>

										<hr />
										<div class="control-group">
											<?php echo $this->formLabel($profileForm->get('dateofbirth')); ?>
											<!-- <label class="control-label" for="form-field-date">Birth Date</label>-->

											<div class="controls">
												<div class="input-append">
													<?php echo $this->formInput($profileForm->get('dateofbirth')); ?>
													<!-- <input class="input-small date-picker" id="form-field-date" type="text" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />-->
													<span class="add-on">
														<i class="icon-calendar"></i>
													</span>
												</div>
											</div>
										</div>

										<div class="control-group">
											<?php echo $this->formLabel($profileForm->get('sex')); ?>
											<!-- <label class="control-label">Gender</label>-->

											<div class="controls">
												<div class="space-2"></div>
											<?php echo $this->formRadio($profileForm->get('sex')); ?>
												<!-- <label class="inline">
													<input name="form-field-radio" type="radio" />
													<span class="lbl"> Male</span>
												</label>

												&nbsp; &nbsp; &nbsp;
												<label class="inline">
													<input name="form-field-radio" type="radio" />
													<span class="lbl"> Female</span>
												</label>-->
											</div>
										</div>


										<div class="space"></div>
										<h4 class="header blue bolder smaller">Contact</h4>

										<div class="control-group">
										<?php echo $this->formLabel($profileForm->get('email')); ?>
											<!-- <label class="control-label" for="form-field-email">Email</label>-->

											<div class="controls">
												<span class="input-icon input-icon-right">
													<?php echo $this->formInput($profileForm->get('email')); ?>
													<!-- <input type="email" id="form-field-email" value="alexdoe@gmail.com" />-->
													<i class="icon-envelope"></i>
												</span>
											</div>
										</div>

										<div class="control-group">
										<?php echo $this->formLabel($profileForm->get('phone')); ?>
											<!-- <label class="control-label" for="form-field-phone">Phone</label>-->

											<div class="controls">
												<span class="input-icon input-icon-right">
												<?php echo $this->formInput($profileForm->get('phone')); ?>
													<!-- <input class="input-medium input-mask-phone" type="text" id="form-field-phone" />-->
													<i class="icon-phone icon-flip-horizontal"></i>
												</span>
											</div>
										</div>
										<div class="form-actions">
										<?php echo $this->formButton($profileForm->get('submit')) ?>
											<!-- <button class="btn btn-info" type="button">
												<i class="icon-ok bigger-110"></i>
												Save
											</button>-->
			
											&nbsp; &nbsp; &nbsp;
											<button class="btn" type="reset">
												<i class="icon-undo bigger-110"></i>
												Reset
											</button>
										</div>
									<?php echo $this->form()->closeTag() ?>	
									</div>

									<div id="edit-settings" class="tab-pane">
										<div class="space-10"></div>

										<div>
											<label class="inline">
												<input type="checkbox" name="form-field-checkbox" />
												<span class="lbl"> Make my profile public</span>
											</label>
										</div>

										<div class="space-8"></div>

										<div>
											<label class="inline">
												<input type="checkbox" name="form-field-checkbox" />
												<span class="lbl"> Email me new updates</span>
											</label>
										</div>

									</div>

									<div id="edit-password" class="tab-pane">
										<div class="space-10"></div>

										<div class="control-group">
											<label class="control-label" for="form-field-pass1">New Password</label>

											<div class="controls">
												<input type="password" id="form-field-pass1" />
											</div>
										</div>

										<div class="control-group">
											<label class="control-label" for="form-field-pass2">Confirm Password</label>

											<div class="controls">
												<input type="password" id="form-field-pass2" />
											</div>
										</div>
									</div>
								</div>
							</div>

<!--							<div class="form-actions">-->
<!--								<button class="btn btn-info" type="button">-->
<!--									<i class="icon-ok bigger-110"></i>-->
<!--									Save-->
<!--								</button>-->
<!---->
<!--								&nbsp; &nbsp; &nbsp;-->
<!--								<button class="btn" type="reset">-->
<!--									<i class="icon-undo bigger-110"></i>-->
<!--									Reset-->
<!--								</button>-->
<!--							</div>-->
						<!-- </form>-->
					</div><!--/span-->
				</div><!--/user-profile-->
			</div>
			<!--PAGE CONTENT ENDS-->
		</div><!--/.span12  -->
	</div><!--/.row-fluid  -->
</div><!--/.page-content  -->

<div class="modal hide fade" id="uploadModal">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h4 class="blue">Change Avatar</h4>
	</div>
	
	<form class="no-margin" id="fileupload" action="" method="POST" enctype="multipart/form-data">
	<div class="modal-body">
		<div class="space-4"></div>
		<div style="width:94%;margin-left:3%;">
		    <div class="gdn-file-input gdn-file-multiple">
			
			<label data-title="Click to choose new avatar">
                <input type="file" name="files[]" id="input_file">
			    <span data-title="No File ..."><i class="icon-picture"></i></span>
			</label>
			<a href="#" class="remove"><i class="icon-remove"></i></a>
		    </div>
		    <div class="gdn-file-preview">
			<div class="files"></div>
		    </div>
		</div>
	</div>
	
	<div class="modal-footer center">
		<button type="button" class="btn btn-small btn-success submit-button"><i class="icon-ok"></i> Submit</button>
		<button type="button" class="btn btn-small" data-dismiss="modal"><i class="icon-remove"></i> Cancel</button>
	</div>
	</form>
</div>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class="template-upload">
	<span class="preview"></span>
	<strong class="error red"></strong>
	<p class="size">Processing...</p>
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar progress-bar-success" style="width:0%;"></div></div>
	{% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel btn-upload-cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
    </div>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class="template-download gdn-dashed">
	    {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}     
            {% if (file.deleteUrl) { %}
                <a href="#" class="delete delete-image remove" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="icon-remove"></i>
                </a>
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}     
	<span class="preview">
	    {% if (file.mediumUrl) { %}
		<span class="profile-picture"><img src="{%=file.mediumUrl%}" id="target"></span>
	    {% } %}
	</span> 
	<div id="preview-pane" class="hide">
	    <div class="preview-container">
	      <img src="{%=file.mediumUrl%}" class="jcrop-preview" alt="Preview" />
	    </div>	    
	</div>               
    </div>
{% } %}
</script>

<?php $this->inlineScript()
	->appendFile($this->basePath() . '/assets/js/godana.validate.js')
	->appendFile($this->basePath() . '/assets/plugins/datepicker/js/bootstrap-datepicker.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/tmpl.min.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/load-image.min.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/canvas-to-blob.min.js')	
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.iframe-transport.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload-process.js')	
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload-image.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload-audio.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload-video.js')	
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload-validate.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.fileupload-ui.js')
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/jquery.Jcrop.js')	
	->appendFile($this->basePath() . '/assets/plugins/file-upload/js/upload.godana.js');
?>


<script type="text/javascript">
var ajaxUrl = "<?=$this->url('upload', array(), array(), true); ?>";
var cropUrl = "<?=$this->url('crop', array(), array(), true); ?>";
var validateUrl = "<?=$this->url('zfcuser/input_validate', array(), array(), true); ?>";
var profileUrl = "<?=$this->url('zfcuser/admin', array(), array(), true); ?>";
$(function() {
	$(".datepicker").datepicker();
	$('.edit-profile').on('click', function(e){
		$('.user-profile').parent().hide();
		$('#user-profile-edit').parent().show();
		return false;
	});
	$('.view-profile').on('click', function(e){
		$('.user-profile').parent().hide();
		$('#user-profile-view').parent().show();
		return false;
	});
	$('.show-modal').imageupload({
		doCrop: true,
		uploadUrl: ajaxUrl+'?type=user',
		cropUrl: cropUrl
	});	
	$("form#profileForm").submit(function(e) {
		$('.control-group').removeClass('error');
    	$('.control-group').find('.help-block').remove();	
		e.preventDefault();
		$.ajax({
        	type: "POST",
            url: profileUrl,
            data: $("form#profileForm").serialize(),
            dataType: "json",
			beforeSend: function() {    
    			//$('.register-button').addClass('disabled');
				$('.update-profile-button').addClass('disabled');
				$('.gdn-loading').removeClass('icon-ok').addClass('icon-spinner icon-spin');
    		},
            success: function(res) {
                if (res.success == false) {
                	$("form#profileForm .my-alert").html(res.alert);
                	$('.update-profile-button').removeClass('disabled');  
                	$('.gdn-loading').addClass('icon-remove').removeClass('icon-spinner icon-spin');
                	
                	for (var i = 0; i < res.error.length; i++) {
                    	var error = res.error[i];
                    	var name = error.name;
                    	var value = error.value;
                    	var $element = $('input[name="'+name+'"]');
                    	$element.parents('.control-group').addClass('error');
                    	if ($element.parents('.controls').length > 0) {
                    		$element.parents('.controls').append(value);
                    	} else {
                    		$element.parents('.control-group').append(value);
                    	} 
                	}     	
                } else {
                	$("form#profileForm .my-alert").html(res.alert);
                	$('.update-profile-button').removeClass('disabled');
                	$('.gdn-loading').addClass('icon-ok').removeClass('icon-spinner icon-spin');
                }
    		}
        });
        return false;
	});
});
</script>