<? $this->headTitle($this->translate('Login'));?>
<?php
$loginForm = $this->loginForm;
$loginForm->prepare();
$loginForm->setAttribute('action', '');
$loginForm->setAttribute('method', 'post');
$loginForm->setAttribute('id', 'loginForm');

$registerForm = $this->registerForm;
$registerForm->prepare();
$registerForm->setAttribute('action', '');
$registerForm->setAttribute('method', 'post');
$registerForm->setAttribute('id', 'registerForm');

$forgotForm = $this->forgotForm;
$forgotForm->prepare();
$forgotForm->setAttribute('action', '');
$forgotForm->setAttribute('method', 'post');
$forgotForm->setAttribute('id', 'forgotForm');
?>
<div class="main-content">
	<div class="row-fluid">
		<div class="span12">
			<div class="login-container">
				<div class="row-fluid">
					<div class="center block">
						<a href="<?=$this->url('home', array(), array(), true) ?>"><img id="logo-header" src="<?php echo $this->basePath();?>/assets/img/logo-godana2.png" alt="Logo"/></a>
					</div>
				</div>

				<div class="space-6"></div>

				<div class="row-fluid">
					<div class="position-relative">
						<div id="login-box" class="login-box visible widget-box no-border">
							<div class="widget-body">
								<div class="widget-main">
									<h4 class="header blue lighter bigger">										
										<?php echo $this->translate('Please Enter Your Information'); ?>
									</h4>

									<div class="space-6"></div>

									<?php echo $this->form()->openTag($loginForm) ?>
									<div class="my-alert"></div>
										<fieldset>
											<label>
												<span class="block input-icon input-icon-right">												
													<?php echo $this->formInput($loginForm->get('identity')) ?>
													<i class="icon-user"></i>
												</span>
											</label>

											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($loginForm->get('credential')) ?>
													<i class="icon-lock"></i>
												</span>
											</label>

											<div class="space"></div>

											<div class="clearfix">
												<label class="inline">
													<?php echo $this->formCheckbox($loginForm->get('remember_me')) ?>
													<span class="lbl"> <?php echo $this->translate('Remember me') ?></span>
												</label>

												<button onclick="" class="width-35 pull-right btn btn-small btn-primary login-button">
													<i class="icon-key"></i>
													Login
												</button>
											</div>

											<div class="space-4"></div>
										</fieldset>
									<?php echo $this->form()->closeTag() ?>

									<div class="social-or-login center">
										<span class="bigger-110">Or Login Using</span>
									</div>

									<div class="social-login center">
										<a class="btn btn-primary">
											<i class="icon-facebook"></i>
										</a>

										<a class="btn btn-info">
											<i class="icon-twitter"></i>
										</a>

										<a class="btn btn-danger">
											<i class="icon-google-plus"></i>
										</a>
									</div>
								</div><!--/widget-main-->

								<div class="toolbar clearfix">
									<div>
										<a href="#" onclick="show_box('forgot-box'); return false;" class="forgot-password-link">
											<i class="icon-arrow-left"></i>
											I forgot my password
										</a>
									</div>

									<div>
										<a href="#" onclick="show_box('signup-box'); return false;" class="user-signup-link">
											I want to register
											<i class="icon-arrow-right"></i>
										</a>
									</div>
								</div>
							</div><!--/widget-body-->
						</div><!--/login-box-->

						<div id="forgot-box" class="forgot-box widget-box no-border">
							<div class="widget-body">
								<div class="widget-main">
									<h4 class="header red lighter bigger">
										<i class="icon-key"></i>
										Retrieve Password
									</h4>

									<div class="space-6"></div>
									<p>
										Enter your email to receive instructions
									</p>

									<?php echo $this->form()->openTag($forgotForm) ?>
									<div class="my-alert"></div>
										<fieldset>
											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($forgotForm->get('email')) ?>
													<i class="icon-envelope"></i>
												</span>
											</label>

											<div class="clearfix">
												<button onclick="" class="width-35 pull-right btn btn-small btn-danger forgot-button">
													<i class="icon-lightbulb"></i>
													Send Me!
												</button>
											</div>
										</fieldset>
									<?php echo $this->form()->closeTag() ?>
								</div><!--/widget-main-->

								<div class="toolbar center">
									<a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
										Back to login
										<i class="icon-arrow-right"></i>
									</a>
								</div>
							</div><!--/widget-body-->
						</div><!--/forgot-box-->

						<div id="signup-box" class="signup-box widget-box no-border">
							<div class="widget-body">
								<div class="widget-main">
									<h4 class="header green lighter bigger">
										<i class="icon-group blue"></i>
										New User Registration
									</h4>

									<div class="space-6"></div>
									<p> Enter your details to begin: </p>

									<?php echo $this->form()->openTag($registerForm) ?>									
										<fieldset>
                                            <label class="my-alert"></label>
											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($registerForm->get('email')) ?>
													<i class="icon-envelope"></i>
												</span>
											</label>

											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($registerForm->get('username')) ?>
													<i class="icon-user"></i>
												</span>
											</label>

											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($registerForm->get('password')) ?>
													<i class="icon-lock"></i>
												</span>
											</label>

											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($registerForm->get('passwordVerify')) ?>
													<i class="icon-retweet"></i>
												</span>
											</label>
											
											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formCaptcha($registerForm->get('captcha')) ?>
												</span>
											</label>

											<label>
												<input type="checkbox" required="required"/>
												<span class="lbl">
													I accept the
													<a href="#">User Agreement</a>
												</span>
											</label>

											<div class="space-24"></div>

											<div class="clearfix">
												<button type="reset" class="width-30 pull-left btn btn-small">
													<i class="icon-refresh"></i>
													Reset
												</button>

												<button onclick="" class="width-65 pull-right btn btn-small btn-success register-button">
													Register
													<i class="icon-arrow-right icon-on-right"></i>
												</button>
											</div>
										</fieldset>
									<?php echo $this->form()->closeTag() ?>
								</div>

								<div class="toolbar center">
									<a href="#" onclick="show_box('login-box'); return false;" class="back-to-login-link">
										<i class="icon-arrow-left"></i>
										Back to login
									</a>
								</div>
							</div><!--/widget-body-->
						</div><!--/signup-box-->
					</div><!--/position-relative-->
				</div>
			</div>
		</div><!--/.span-->
	</div><!--/.row-fluid-->
</div>
<?php $this->inlineScript()
	->appendFile($this->basePath() . '/assets/js/godana.validate2.js');?>
<script type="text/javascript">
var loginUrl = "<?php echo $this->url('zfcuser/login', array(), array(), true); ?>";
var validateUrl = "<?=$this->url('zfcuser/input_validate', array(), array(), true); ?>";
var registerUrl = "<?=$this->url('zfcuser/register', array(), array(), true); ?>";
var forgotUrl = "<?=$this->url('zfcuser/forgotpassword', array(), array(), true); ?>";
$(document).ready(function() {	

	$('button[type="reset"]').click(function() {
		$('label').removeClass('register-error').removeClass('register-valid');
		$('label').find('.help-block').remove();
	});
	$('#register_email').validateInput({
		name: 'email',
		url: validateUrl,
		query: '&type=register'
	});
	$('#register_username').validateInput({
		name: 'username',
		url: validateUrl,
		query: '&type=register'
	});
	$('#register_password').validateInput({
		name: 'password',
		url: validateUrl,
		query: '&type=register'
	});

	$('input[name="captcha[input]"]').validateInput({
		name: 'captcha[input]',
		url: validateUrl,
		query: '&captcha[id]='+$('input[name="captcha[id]"]').val()+'&type=register'
	});
	
	$('#register_password').change(function(e) {
		var password = $(this).val();
		$('#register_password_verify').validateInput("destroy");
		$('#register_password_verify').validateInput("init", {
			name: 'passwordVerify',
			query: '&password='+password+'&type=register',
			url: validateUrl			
		});	
		
	});
	$("form#loginForm").submit(function(e) {
		e.preventDefault();
		$.ajax({
        	type: "POST",
            url: loginUrl,
            data: $("form#loginForm").serialize(),
            dataType: "json",
			beforeSend: function() {    
    			$('.login-button').addClass('disabled');
    		},
            success: function(res) {
                if (res.success == false) {
                	$("form#loginForm .my-alert").html(res.alert);
                	$('.login-button').removeClass('disabled');                	
                } else {
                	$(location).attr('href',res.redirect);  
                }
    		}
        });
        return false;
	});

	$("form#registerForm").submit(function(e) {
		e.preventDefault();
		if (($("#captcha-challenge").length > 0) && ($("#captcha-response").length > 0)) {
			$("#captcha-challenge").val($("#recaptcha_challenge_field").val());
	        $("#captcha-response").val($("#recaptcha_response_field").val());
		} 
        
		$.ajax({
        	type: "POST",
            url: registerUrl,
            data: $("form#registerForm").serialize(),
            dataType: "json",
			beforeSend: function() {    
    			$('.register-button').addClass('disabled');
    		},
            success: function(res) {
                if (res.success == false) {
                	$("form#registerForm .my-alert").html(res.alert);
                	$('.register-button').removeClass('disabled');                	
                } else {
                	$(location).attr('href',res.redirect);  
                }
    		}
        });
        return false;
	});

	$('#forgot_email').validateInput({
		name: 'email',
		url: validateUrl,
		query: '&type=forgot'
	});

	$("form#forgotForm").submit(function(e) {
		e.preventDefault();
		$.ajax({
        	type: "POST",
            url: forgotUrl,
            data: $("form#forgotForm").serialize(),
            dataType: "json",
			beforeSend: function() {    
    			$('.forgot-button').addClass('disabled');
    		},
            success: function(res) {
                if (res.success == false) {
                	$("form#forgotForm .my-alert").html(res.alert);
                	$('.forgot-button').removeClass('disabled');                	
                } else {
                	$(location).attr('href',res.redirect);  
                }
    		}
        });
        return false;
	});
	
});
</script>