<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/datepicker3.css')?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Edit user'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('User changed successfully.'); ?> 
</div>
<? endif;?>
<?php
$form = $this->userEditForm;
$form->prepare();
$user = $this->user;
$userId = $user->getId();
$form->setAttribute('action', $this->url('admin/user/edit', array('lang' => $lang, 'userId' => $userId)));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form) ?>

<? $userForm = $form->get('user-form');?>
<? echo $this->formHidden($userForm->get('id'));?>
<? $firstname = $userForm->get('firstname'); ?>
<div class="form-group <?php if($this->formElementErrors($firstname)) 
echo "has-error" ?>">
<?php echo $this->formLabel($firstname); ?>
<div class="col-sm-7">
<?php echo $this->formElement($firstname) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($firstname); ?>
</div>
</div>

<? $lastname = $userForm->get('lastname'); ?>
<div class="form-group <?php if($this->formElementErrors($lastname)) 
echo "has-error" ?>">
<?php echo $this->formLabel($lastname); ?>
<div class="col-sm-7">
<?php echo $this->formElement($lastname) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($lastname); ?>
</div>
</div>

<? $dateofbirth = $userForm->get('dateofbirth'); ?>
<div class="form-group <?php if($this->formElementErrors($dateofbirth)) 
echo "has-error" ?>">
<?php echo $this->formLabel($dateofbirth); ?>
<div class="col-sm-7">
<?php echo $this->formElement($dateofbirth) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($dateofbirth); ?>
</div>
</div>

<? $sex = $userForm->get('sex'); ?>
<div class="form-group <?php if($this->formElementErrors($sex)) 
echo "has-error" ?>">
<?php echo $this->formLabel($sex); ?>
<div class="col-sm-7">
<?php echo $this->formElement($sex) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($sex); ?>
</div>
</div>

<div class="form-group">
    <label class="col-sm-3 control-label"><?=$this->translate('Email') ?></label>
    <div class="col-sm-7">
      <p class="form-control-static"><?=$user->getEmail(); ?></p>
    </div>
</div>

<? $rolesCollection = $userForm->get('roles');?>

<div id="roles-group">
	<? foreach ($rolesCollection as $c):?>
	<div class="roles-element">
		<div class="form-group">
			<?=$this->formLabel($c->get('id')); ?>
			<div class="col-sm-7">
			<?=$this->formElement($c->get('id')); ?>			
			</div>
		</div>		
	</div>
	<? endforeach;?>
</div>
<div class="form-group">
	<span id="tplRole" data-template="<?=htmlspecialchars('<div class="roles-element"><div class="form-group"><label for="roles[__placeholder__][id]" class="col-sm-3 control-label">Role</label><div class="col-sm-7"><select name="roles[__placeholder__][id]" id="role-chosen-__placeholder__" class="form-control role-select"><option value="1">guest</option>
	<option value="2">user</option>
	<option value="3">moderator</option>
	<option value="4">admin</option>
	<option value="5">shop-owner</option></select></div></div>');?>"></span>
	<div class="col-sm-7 col-sm-offset-3"></div>
</div>

<? echo $this->formHidden($form->get('csrf'));?>

<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')
			->appendFile($this->basePath() . '/js/bootstrap-datepicker.js')
			->appendFile($this->basePath() . '/js/bootstrap-datepicker.js')?>
			
<script type="text/javascript">
$(function() {
	$(".role-select").select2({
		minimumResultsForSearch: 10
	});
	$(".chosen-select").select2({
		minimumResultsForSearch: 10
	});
	$(".datepicker").datepicker({
		//language: 'fr'
	});
	/* ADDING MORE ROLE */
	var tplRole = $('#tplRole');
	var tplRoleManager = tplRole.parent();
	var rolesGroup = $('#roles-group');
	
	
	var addRole = function () {	    	    
		var rolesCount = rolesGroup.find('.roles-element').length;
	    rolesGroup.append(tplRole.data('template').replace(/__placeholder__/g, rolesCount));
	    return rolesCount;
	};

	var removeBtnRoles =  $('<button class="btn btn-primary col-sm-offset-1"><i class="glyphicon glyphicon-minus"></i> <?=$this->translate('Role'); ?></button>')
    .button({
        icons: {
            primary: 'ui-icon-circle-plus'
        }
    }).on('click', function(e) {
        e.preventDefault();        
        count = rolesGroup.find('.roles-element').length;
        if (count == 2) {
        	rolesGroup.find('.roles-element:last-child').remove();
            $(this).remove();
        } else {
        	rolesGroup.find('.roles-element:last-child').remove();
        }
    });

	

	var btnRoles = $('<button class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('Role'); ?></button>')
	    .button({
	        icons: {
	            primary: 'ui-icon-circle-plus'
	        }
	    }).on('click', function (e) {
	    	tplRoleManager.find('div').append(removeBtnRoles);
	        e.preventDefault();
	        $('.removeElement').html('');
	        var index = addRole();
	        $("#role-chosen-"+index).select2({ 
	    		width: '100%',
	    		minimumResultsForSearch: 10
	    	});
	        //addRemoveButton('#roles');
	    });

	tplRoleManager.find('div').append(btnRoles);
	var initRolesCount = rolesGroup.find('.roles-element').length;
	if (initRolesCount > 1) {	
		tplRoleManager.find('div').append(removeBtnRoles);
	}
});
</script>