<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/DT_bootstrap.css');?>
<? $this->headTitle($this->translate('User'));?>
<div class="row">
<div class="col-md-12">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('User'); ?></h3>
</div>
<div class="panel-body">
<? $users = $this->users;?>
<div class="table-responsive">
<table id="example" class="table table-striped table-bordered dataTable">
<thead><tr><th>#&nbsp;</th><th><?=$this->translate('First name'); ?></th><th><?=$this->translate('Last name'); ?></th>
<th><?=$this->translate('Email'); ?></th><th><?=$this->translate('Role'); ?></th><th><?=$this->translate('Action'); ?></th></tr></thead>
<tbody>
<? foreach($users as $user):?>
<? $roles = $user->getRoles();?>
<? $roleToDisplay = '';?>
<? foreach ($roles as $role):?>
<? $roleToDisplay .= $role->getRoleId() . '; ';?>
<? endforeach;?>
<? $roleToDisplay = rtrim($roleToDisplay, '; ');?>
<tr><td><?=$user->getId();?></td><td><?=ucfirst($user->getFirstname()); ?></td><td><?=ucfirst($user->getLastname()); ?></td>
<td><?=$user->getEmail();?></td><td><?=$roleToDisplay; ?></td>
<td><a class="btn btn-primary btn-xs" href="<?=$this->url('admin/user/role_change', array('lang' => $this->lang, 'userId' => $user->getId()), array(), true); ?>"><?=$this->translate('Change role'); ?></a>&nbsp;<a class="btn btn-primary btn-xs" href="<?=$this->url('admin/user/edit', array('lang' => $this->lang, 'userId' => $user->getId()), array(), true); ?>"><?=$this->translate('Edit user'); ?></a></td></tr>
<? endforeach;?>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/jquery.dataTables.min.js')
			->appendFile($this->basePath() . '/js/DT_bootstrap.js');?>