<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login', array(), array(), true));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>
<div class="margin-top-40 log-page">
<?php echo $this->form()->openTag($form) ?>
<h3 class="center">Login to your account</h3>
<? if($this->formElementErrors($form->get('identity'))): ?>
<div class="alert alert-danger alert-dismissable">
<button data-dismiss="alert" class="close">×</button>
    	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div>')
                ->setMessageSeparatorString('</div><div>')
                ->setMessageCloseString('</div>')
                ->render($form->get('identity')); ?>
</div>
<? endif;?>
<div class="input-prepend">
	<span class="add-on"><i class="icon-user"></i></span>
	<?php echo $this->formInput($form->get('identity')) ?>
</div>
<div class="input-prepend">
	<span class="add-on"><i class="icon-lock"></i></span>
	<?php echo $this->formInput($form->get('credential')) ?>
</div>
<div class="controls form-inline">
	<label class="checkbox"><input type="checkbox" /> Stay Signed in</label>
	<?php echo $this->formButton($form->get('submit')) ?>
</div>
<?php echo $this->form()->closeTag() ?>
<div class="social-or-login center">
	<span class="bigger-110">Or Login Using</span>
</div>
<div class="social-login center">
<?php     echo $this->mySocialSignInButton('facebook') ?>	
</div>

<div class="gdn-register center">
<a href="<?php echo $this->url('zfcuser/register', array(), array(), true) . 
($this->redirect ? '?redirect='.$this->redirect : '') ?>" class="btn-u btn-u-red btn-block"><?php echo $this->translate('Sign up'); ?></a>
</div>
</div>

<script type="text/javascript">
$(function() {
	window.setTimeout(function() {
		$('.alert').fadeOut("slow");
	}, 3000);
});
</script>