<? $this->headTitle($this->translate('Login'));?>
<div class="main-content">
	<div class="row-fluid">
		<div class="span12">
			<div class="login-container">
				<div class="row-fluid">
					<div class="center block">
						<a href="<?=$this->url('home', array(), array(), true) ?>"><img id="logo-header" src="<?php echo $this->basePath();?>/assets/img/logo-godana2.png" alt="Logo"/></a>
					</div>
				</div>

				<div class="space-6"></div>

				<div class="row-fluid">
					<div class="position-relative">
						<div class="forgot-box widget-box no-border visible">
							<div class="widget-body">
								<div class="widget-main">
									<h4 class="header red lighter bigger">
										<i class="icon-key"></i>
										Retrieve Password
									</h4>

									<div class="space-6"></div>									
									<div class="alert alert-info">
										<h5><?=$this->translate('Your password has been changed. You can now login using your new password.'); ?></h5>
									</div>
								</div><!--/widget-main-->

								<div class="toolbar center">
									<a href="<?=$this->url('zfcuser/login', array(), array(), true) ?>" class="back-to-login-link">
										<?php echo $this->translate('Back to login'); ?>
										<i class="icon-arrow-right"></i>
									</a>
								</div>
							</div><!--/widget-body-->
						</div><!--/forgot-box-->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
