<?php echo $this->headLink()
				->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/datepicker3.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.fileupload.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.fileupload-ui.css')
                ->appendStylesheet($this->basePath() . '/css/jquery.Jcrop.min.css');?>
<? $this->headTitle($this->translate('Profile'));?>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Your profile is updated.'); ?> 
</div>
<? endif;?>
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    print "</div></div></div></div>";
    return;
}
$form = $this->profileForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/profile', array(), array(), true));
$form->setAttribute('method', 'post');
?>
<div class="gdn_form_area">
<?php echo $this->form()->openTag($form) ?>
	<div class="form-group">
	    <label class="sr-only"><?=$this->translate('Profile picture') ?></label>
	    <div class="gdn_input_margin">
	      	<img src="<?=$this->userPicture('sm'); ?>" class="img-thumbnail"/>
	      	<button class="btn btn-default show-modal">
				<i class="fa fa-picture-o"></i>
				<span><?=$this->translate('Change image'); ?></span>
			</button>
	    </div>
	  </div>
	
	<?php foreach ($form as $element): ?>
		<div class="form-group <?php if($this->formElementErrors($element)) 
                                echo "has-error" ?>">
		<?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formLabel($element); ?>
        <?php endif; ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <div class="col-sm-3 col-sm-offset-3 col-xs-6 col-xs-offset-1"><?php echo $this->formButton($element) ?></div>
            <a class="btn btn-default" href="<?php echo $this->url('zfcuser/changepassword', array(), array(), true) . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?=$this->translate('Change password'); ?></a>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <div class="gdn_input_margin"><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>
        <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
        	<div class="gdn_input_margin">
        		<?php echo $this->formSelect($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
        	</div>
        <?php else: ?>
            <div class="gdn_input_margin">
            	<?php echo $this->formInput($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
            </div>
        <?php endif ?>
        </div>
	<?php endforeach; ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
    <div class="listFileId"></div>
	
    
<?php echo $this->form()->closeTag() ?>
</div><!-- /.form_area -->
</div><!-- /.panel-body -->
</div><!-- /.panel -->
</div><!-- /.col-md-6 -->
</div><!-- /.row -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog wide-modal">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><?=$this->translate('Upload image'); ?></h4>
      </div>
      <div class="modal-body modal-body-modified">
		<? 
      	$form = $this->fileForm;
		$form->prepare();
		$form->setAttribute('class', 'form-inline');
		echo $this->form()->openTag($form);
		$elem = $form->get('files');
		?>
		<div class="row fileupload-buttonbar">
            <div class="container media-content">
            	<div class="row row-media hide">
	            	<div class="col-md-8 image-preview-container">
	            		<div class="container ">
	            			<div class="row files"></div>		
	            		</div>
	            	</div>
					<div class="col-md-4 image-edit-container">
	            		<div class="container ">
	            			<div class="row"><div class="col-md-12"><div class="image-detail-container"></div></div></div>		
	            		</div>
	            	</div>
            	</div>
            	<div class="row row-upload">
					<div class="img-selection center-block center-vertical">
						<div class="file-upload-btn ">
							<span class="btn btn-default btn-lg  fileinput-button">
			                    <span><?=$this->translate('Add images'); ?></span>
			                    <?php echo $this->formFile($elem); ?>
							</span>
		                </div>		
		                <?=$this->translate('or'); ?>               
						<button class="btn btn-default btn-lg btn-choose"><?=$this->translate('Choose images'); ?></button>
					</div>
            	</div>
			</div>
        </div>
         <?php echo $this->form()->closeTag($form); ?>
      </div><!-- /.modal-body -->      
      
      <div class="modal-footer modal-footer-modified">
		<button class="btn btn-default btn-preview-add-image pull-left hide"><?=$this->translate('Add images'); ?></button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('Close'); ?></button>
        <button type="button" id="save-images" class="btn btn-primary" disabled="disabled"><?=$this->translate('Insert into post'); ?></button>
      </div><!-- /.modal-footer -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
<div class="col-md-4 template-upload fade">
{% if (i) { %}
	<span class="preview">
       	{% if (file.thumbnailUrl) { %}
           	<a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
    	{% } %}
		
	</span>
{% } else { %}
	<div class="my-progress fileupload-progress fade">
		<div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
			<div class="progress-bar progress-bar-success" style="width:0%;"></div>
		</div>
	</div>
	<strong class="error text-danger"></strong>
	<button class="btn btn-warning cancel">
    	<i class="glyphicon glyphicon-ban-circle"></i>
        <span>Cancel</span>
	</button>
{% } %}
</div>
{% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
{% if (file.thumbnailUrl) { %}
	<div class="col-md-4 template-download fade">
		<span class="preview">		
			<img src="{%=file.thumbnailUrl%}" class="img-thumbnail img-thumbnail-preview">
			<span class="my-zoom-icon">
				<a href='#' data-toggle="tooltip" title="Deselect" class="deselect my-tooltip"><span class="glyphicon glyphicon-minus"></span></a> 
				<a href="#" data-toggle="tooltip" title="Crop" class="crop my-tooltip"><span class="glyphicon glyphicon-th"></span></a> 
				<a href="#" class="delete my-tooltip"  data-toggle="tooltip" title="Delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}><span class="glyphicon glyphicon-remove"></span></a>
			</span>
			<input type="hidden" class="fileId" value="{%=file.id%}"/>		
		
			<input type="checkbox" name="delete" value="1" class="toggle hidden">
		</span>	
	</div>
{% } %}
{% if (file.error) { %}
	<div class="col-md-4 template-download fade">
    	<div class="error-file"><span class="label label-danger">Error</span> {%=file.error%}</div>
	</div>
		{% } %}
{% } %}
</script>

<?php $this->inlineScript()
	->appendFile($this->basePath() . '/js/bootstrap-datepicker.js')
	->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js')
	->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.mg.js')
	->appendFile($this->basePath() . '/js/select2.min.js')
	//->appendFile($this->basePath() . '/js/user-upload.js')
	->appendFile($this->basePath() . '/js/jquery.godana.js')
	->appendFile($this->basePath() . '/js/vendor/jquery.ui.widget.js')
    ->appendFile($this->basePath() . '/js/tmpl.min.js')
    ->appendFile($this->basePath() . '/js/load-image.min.js')
    ->appendFile($this->basePath() . '/js/canvas-to-blob.min.js')
    ->appendFile($this->basePath() . '/js/jquery.blueimp-gallery.min.js')
    ->appendFile($this->basePath() . '/js/jquery.iframe-transport.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload-process.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload-video.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload-ui.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload-validate.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload-image.js')
    ->appendFile($this->basePath() . '/js/jquery.fileupload-audio.js')
    ->appendFile($this->basePath() . '/js/jquery.Jcrop.min.js');
?>
<script type="text/javascript">
var language = "<?=$this->lang?>";
var ajaxUrl = "<?=$this->url('upload', array(), array(), true); ?>";
var cropUrl = "<?=$this->url('crop', array(), array(), true); ?>";
$(function() {
	$(".datepicker").datepicker({language: language});
	window.setTimeout(function() {
		$('.alert').fadeOut("slow");
	}, 3000);
	$(".sex-select").select2({
		placeholder: "<?=$this->translate('Sex') ?>",
		minimumResultsForSearch: 10
	});
	$('.show-modal').godana({
		ajaxUrl: ajaxUrl+'?type=user',
        cropUrl: cropUrl
	});
	$('#save-images').click(function(e) {
		$('.fileId').each(function() {
			if ($(this).hasClass('file-selected')) {				
	   			$('.listFileId').append('<input type="hidden" name="file-id[]" class="file-id" value="'+$(this).val()+'">');
			}   		
		});
		$('#myModal').modal('hide');		
		return false;
	});
});
</script>