<?php echo $this->headLink()
				->appendStylesheet($this->basePath() . '/assets/plugins/select2/css/select2.css')
                ->appendStylesheet($this->basePath() . '/assets/plugins/select2/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/assets/plugins/datepicker/css/datepicker3.css');?>
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('class', 'reg-page');
$form->setAttribute('action', $this->url('zfcuser/register', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<div class="margin-top-40 row-fluid">
	<?php echo $this->form()->openTag($form) ?>
		<h3 class="center">Register to your account</h3>
		<div class="control-group <?php if($this->formElementErrors($form->get('email'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('email')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formInput($form->get('email')) ?>
            	<span class="pull-right loading-email"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('email')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('username'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('username')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formInput($form->get('username')) ?>
            	<span class="pull-right loading-username"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('username')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('firstname'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('firstname')); ?>
           	<span class="color-red">*</span>           	
			<div class="controls">
            	<?php echo $this->formInput($form->get('firstname')) ?>
            	<span class="pull-right loading-firstname"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('firstname')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('lastname'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('lastname')); ?>
			<div class="controls">
            	<?php echo $this->formInput($form->get('lastname')) ?>
            	<span class="pull-right loading-lastname"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('lastname')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('dateofbirth'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('dateofbirth')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formInput($form->get('dateofbirth')) ?>
            	<span class="pull-right loading-dateofbirth"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('dateofbirth')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('sex'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('sex')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formSelect($form->get('sex')) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('sex')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('password'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('password')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formInput($form->get('password')) ?>
            	<span class="pull-right loading-password"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('password')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('passwordVerify'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('passwordVerify')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formInput($form->get('passwordVerify')) ?>
            	<span class="pull-right loading-passwordVerify"></span>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('passwordVerify')); ?>
            </div>
		</div>
		<div class="control-group <?php if($this->formElementErrors($form->get('captcha'))) 
                                echo "error" ?>">
           	<?php echo $this->formLabel($form->get('captcha')); ?>
           	<span class="color-red">*</span>
			<div class="controls">
            	<?php echo $this->formCaptcha($form->get('captcha')) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($form->get('captcha')); ?>
            </div>
		</div>
		<?php echo $this->formButton($form->get('submit')) ?>
	    <?php if ($this->redirect): ?>
	        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
	    <?php endif ?>
	<?php echo $this->form()->closeTag() ?>

</div><!-- /.row-fluid -->
<?php $this->inlineScript()
	->appendFile($this->basePath() . '/assets/js/godana.validate.js')
	->appendFile($this->basePath() . '/assets/plugins/datepicker/js/bootstrap-datepicker.js')
	->appendFile($this->basePath() . '/assets/plugins/select2/js/select2.min.js');
?>
<script type="text/javascript">
var language = "<?=$this->lang?>";
var url = "<?=$this->url('zfcuser/input_validate', array(), array(), true); ?>";
$(function() {
	$(".datepicker").datepicker();
	$(".sex-select").select2({
		placeholder: "<?=$this->translate('Sex') ?>",
		minimumResultsForSearch: 10
	});
	$('input[name="email"]').validateInput({
		name: 'email',
		loadingClass: '.loading-email',
		url: url
	});
	$('input[name="username"]').validateInput({
		name: 'username',
		loadingClass: '.loading-username',
		url: url
	});
	$('input[name="firstname"]').validateInput({
		name: 'firstname',
		loadingClass: '.loading-firstname',
		url: url
	});
	$('input[name="lastname"]').validateInput({
		name: 'lastname',
		loadingClass: '.loading-lastname',
		url: url
	});
	$('input[name="dateofbirth"]').validateInput({
		name: 'dateofbirth',
		loadingClass: '.loading-dateofbirth',
		url: url
	});
	$('input[name="password"]').validateInput({
		name: 'password',
		loadingClass: '.loading-password',
		url: url
	});
	$('input[name="password"]').change(function(e) {
		var password = $(this).val();
		$('input[name="passwordVerify"]').validateInput("destroy");
		$('input[name="passwordVerify"]').validateInput("init", {
			name: 'passwordVerify',
			loadingClass: '.loading-passwordVerify',
			query: '&password='+password,
			url: url			
		});	
		
	});
//	$('input[name="passwordVerify"]').validateInput({
//		name: 'passwordVerify',
//		loadingClass: '.loading-passwordVerify',
//		url: url
//	});
});
</script>