<? $this->headTitle($this->translate('Login'));?>
<?php

$form = $this->resetForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/resetpassword', array('userId' => $this->userId, 'token' => $this->token)));
$form->setAttribute('method', 'post');
?>
<div class="main-content">
	<div class="row-fluid">
		<div class="span12">
			<div class="login-container">
				<div class="row-fluid">
					<div class="center block">
						<a href="<?=$this->url('home', array(), array(), true) ?>"><img id="logo-header" src="<?php echo $this->basePath();?>/assets/img/logo-godana2.png" alt="Logo"/></a>
					</div>
				</div>

				<div class="space-6"></div>

				<div class="row-fluid">
					<div class="position-relative">
						<div class="forgot-box widget-box no-border visible">
							<div class="widget-body">
								<div class="widget-main">
									<h4 class="header red lighter bigger">
										<i class="icon-key"></i>
										Change Password
									</h4>

									<div class="space-6"></div>
									
									<p>
										Enter your new password
									</p>
									
									<?php echo $this->form()->openTag($form) ?>
									<div class="my-alert"></div>
										<fieldset>
											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($form->get('newCredential')) ?>
													<i class="icon-lock"></i>
												</span>
											</label>
											
											<label>
												<span class="block input-icon input-icon-right">
													<?php echo $this->formInput($form->get('newCredentialVerify')) ?>
													<i class="icon-retweet"></i>
												</span>
											</label>

											<div class="clearfix">
												<?php echo $this->formButton($form->get('submit')); ?>
											</div>
										</fieldset>
									<?php echo $this->form()->closeTag() ?>
									
								</div><!--/widget-main-->

								<div class="toolbar center">
									<a href="<?=$this->url('zfcuser/login', array(), array(), true) ?>" class="back-to-login-link">
										<?php echo $this->translate('Back to login'); ?>
										<i class="icon-arrow-right"></i>
									</a>
								</div>
							</div><!--/widget-body-->
						</div><!--/forgot-box-->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>