<?php echo $this->headLink()
				->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')
                ->appendStylesheet($this->basePath() . '/css/datepicker3.css');?>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-default">
<div class="panel-body">
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
?>
<div class="gdn_form_area">
<?php echo $this->form()->openTag($form) ?>
	<?php foreach ($form as $element): ?>
		<div class="form-group <?php if($this->formElementErrors($element)) 
                                echo "has-error" ?>">
		<?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formLabel($element); ?>
        <?php endif; ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
        	<div class="row">
            <div class="col-sm-4 col-sm-offset-4">            
            <?php echo $this->formButton($element) ?></div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <div class="gdn_input_margin"><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></div>
        <?php elseif ($element instanceof Zend\Form\Element\Select): ?>
        	<div class="gdn_input_margin">
        		<?php echo $this->formSelect($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
        	</div>
        <?php else: ?>
            <div class="gdn_input_margin">
            	<?php echo $this->formInput($element) ?>
            	<?php  echo $this->formElementErrors()
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>')
                ->render($element); ?>
            </div>
        <?php endif ?>
        </div>
	<?php endforeach; ?>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

</div><!-- /.form_area -->
</div><!-- /.panel-body -->
</div><!-- /.panel -->
</div><!-- /.col-md-6 -->
</div><!-- /.row -->
<?php $this->inlineScript()
	->prependFile($this->basePath() . '/js/bootstrap-datepicker.js')
	->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.fr.js')
	->appendFile($this->basePath() . '/js/locales/bootstrap-datepicker.mg.js')
	->appendFile($this->basePath() . '/js/select2.min.js');
?>
<script type="text/javascript">
var language = "<?=$this->lang?>";
$(function() {
	$(".datepicker").datepicker({language: language});
	$(".sex-select").select2({
		placeholder: "<?=$this->translate('Sex') ?>",
		minimumResultsForSearch: 10
	});
});
</script>